// Package asn1gen - ASN1C generated code package
/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (https://obj-sys.com).  Version: 7.7.2, Date: 05-Feb-2024.
 *
 * Copyright (c) 2020-2023 Objective Systems, Inc.
 *
 * This software is furnished under a license and may be used and copied
 * only in accordance with the terms of such license and with the
 * inclusion of the above copyright notice. This software or any other
 * copies thereof may not be provided or otherwise made available to any
 * other person. No title to and ownership of the software is hereby
 * transferred.
 *
 * The information in this software is subject to change without notice
 * and should not be construed as a commitment by Objective Systems, Inc.
 *
 * PROPRIETARY NOTICE
 *
 * This software is an unpublished work subject to a confidentiality agreement
 * and is protected by copyright and trade secret law.  Unauthorized copying,
 * redistribution or other use of this work is prohibited.
 *
 * The above notice of copyright on this source code product does not
 * indicate any actual or intended publication of such source code.
 *
 * Command:  asn1c /home/imgadmin/asn1c-v772/golang/sample_per/ngap/ngap.asn -i /home/imgadmin/asn1c-v772/golang/sample_per/ngap -o src -oh src -genprint -genprttostr -gentest -aper -go -genmake src/makefile -prjdir ../ngap
 *
 **************************************************************************/
package asn1gen

const Asn1vIdInitialContextSetup ProcedureCode = 14
const Asn1vIdNGSetup ProcedureCode = 21
const Asn1vMaxPrivateIEs int64 = 65535
const Asn1vMaxProtocolExtensions int64 = 65535
const Asn1vMaxProtocolIEs int64 = 65535
const Asn1vMaxnoofAllowedSNSSAIs int64 = 8
const Asn1vMaxnoofBPLMNs int64 = 12
const Asn1vMaxnoofErrors int64 = 256
const Asn1vMaxnoofPLMNs int64 = 12
const Asn1vMaxnoofServedGUAMIs int64 = 256
const Asn1vMaxnoofTACs int64 = 256
const Asn1vMaxnoofSliceItems int64 = 1024
const Asn1vIdAllowedNSSAI ProtocolIEID = 0
const Asn1vIdAMFName ProtocolIEID = 1
const Asn1vIdAMFSetID ProtocolIEID = 3
const Asn1vIdAMFUENGAPID ProtocolIEID = 10
const Asn1vIdCause ProtocolIEID = 15
const Asn1vIdCriticalityDiagnostics ProtocolIEID = 19
const Asn1vIdDefaultPagingDRX ProtocolIEID = 21
const Asn1vIdGlobalRANNodeID ProtocolIEID = 27
const Asn1vIdGUAMI ProtocolIEID = 28
const Asn1vIdPagingDRX ProtocolIEID = 50
const Asn1vIdPLMNSupportList ProtocolIEID = 80
const Asn1vIdRANNodeName ProtocolIEID = 82
const Asn1vIdRelativeAMFCapacity ProtocolIEID = 86
const Asn1vIdServedGUAMIList ProtocolIEID = 96
const Asn1vIdSliceSupportList ProtocolIEID = 97
const Asn1vIdSupportedTAList ProtocolIEID = 102
const Asn1vIdTimeToWait ProtocolIEID = 107
const Asn1vIdUERetentionInformation ProtocolIEID = 147
const Asn1vIdDownlinkNASTransport ProcedureCode = 4
const Asn1vIdInitialUEMessage ProcedureCode = 15
const Asn1vIdNASNonDeliveryIndication ProcedureCode = 19
const Asn1vIdUplinkNASTransport ProcedureCode = 46
const Asn1vMaxnoofAllowedAreas int64 = 16
const Asn1vMaxnoofEPLMNs int64 = 15
const Asn1vMaxnoofEPLMNsPlusOne int64 = 16
const Asn1vMaxnoofForbTACs int64 = 4096
const Asn1vIdEUTRACGI ProtocolIEID = 25
const Asn1vIdFiveGSTMSI ProtocolIEID = 26
const Asn1vIdIndexToRFSP ProtocolIEID = 31
const Asn1vIdMobilityRestrictionList ProtocolIEID = 36
const Asn1vIdNASPDU ProtocolIEID = 38
const Asn1vIdNRCGI ProtocolIEID = 45
const Asn1vIdOldAMF ProtocolIEID = 48
const Asn1vIdRANPagingPriority ProtocolIEID = 83
const Asn1vIdRANUENGAPID ProtocolIEID = 85
const Asn1vIdRRCEstablishmentCause ProtocolIEID = 90
const Asn1vIdUEAggregateMaximumBitRate ProtocolIEID = 110
const Asn1vIdUEContextRequest ProtocolIEID = 112
const Asn1vIdUserLocationInformation ProtocolIEID = 121
const Asn1vIdPSCellInformation ProtocolIEID = 149
const Asn1vIdLastEUTRANPLMNIdentity ProtocolIEID = 150
const Asn1vIdCNTypeRestrictionsForEquivalent ProtocolIEID = 160
const Asn1vIdCNTypeRestrictionsForServing ProtocolIEID = 161
const Asn1vIdSourceToTargetAMFInformationReroute ProtocolIEID = 171
const Asn1vIdSelectedPLMNIdentity ProtocolIEID = 174
const Asn1vIdNGReset ProcedureCode = 20
const Asn1vMaxnoofNGConnectionsToReset int64 = 65536
const Asn1vIdResetType ProtocolIEID = 88
const Asn1vIdUEAssociatedLogicalNGConnectionList ProtocolIEID = 111
const Asn1vIdErrorIndication ProcedureCode = 9
const Asn1vIdPDUSessionResourceSetup ProcedureCode = 29
const Asn1vMaxnoofMultiConnectivityMinusOne int64 = 3
const Asn1vMaxnoofPDUSessions int64 = 256
const Asn1vMaxnoofQosFlows int64 = 64
const Asn1vIdPDUSessionResourceFailedToSetupListSURes ProtocolIEID = 58
const Asn1vIdPDUSessionResourceSetupListSUReq ProtocolIEID = 74
const Asn1vIdPDUSessionResourceSetupListSURes ProtocolIEID = 75
const Asn1vIdAdditionalULNGUUPTNLInformation ProtocolIEID = 126
const Asn1vIdDataForwardingNotPossible ProtocolIEID = 127
const Asn1vIdNetworkInstance ProtocolIEID = 129
const Asn1vIdPDUSessionAggregateMaximumBitRate ProtocolIEID = 130
const Asn1vIdPDUSessionType ProtocolIEID = 134
const Asn1vIdQosFlowSetupRequestList ProtocolIEID = 136
const Asn1vIdSecurityIndication ProtocolIEID = 138
const Asn1vIdULNGUUPTNLInformation ProtocolIEID = 139
const Asn1vIdMaximumIntegrityProtectedDataRateDL ProtocolIEID = 151
const Asn1vIdCommonNetworkInstance ProtocolIEID = 166
const Asn1vIdPDUSessionResourceRelease ProcedureCode = 28
const Asn1vIdSecondaryRATUsageInformation ProtocolIEID = 144
const Asn1vIdPDUSessionResourceReleasedListRelRes ProtocolIEID = 70
const Asn1vIdPDUSessionResourceToReleaseListRelCmd ProtocolIEID = 79
const Asn1vMaxnoofCellinAoI int64 = 256
const Asn1vMaxnoofCellsUEMovingTrajectory int64 = 16
const Asn1vMaxnoofMultiConnectivity int64 = 4
const Asn1vMaxnoofRANNodeinAoI int64 = 64
const Asn1vMaxnoofAoI int64 = 64
const Asn1vMaxnoofTAIforInactive int64 = 16
const Asn1vMaxnoofTAIinAoI int64 = 16
const Asn1vIdCoreNetworkAssistanceInformationForInactive ProtocolIEID = 18
const Asn1vIdEmergencyFallbackIndicator ProtocolIEID = 24
const Asn1vIdLocationReportingRequestType ProtocolIEID = 33
const Asn1vIdMaskedIMEISV ProtocolIEID = 34
const Asn1vIdPDUSessionResourceFailedToSetupListCxtRes ProtocolIEID = 55
const Asn1vIdPDUSessionResourceSetupListCxtReq ProtocolIEID = 71
const Asn1vIdPDUSessionResourceSetupListCxtRes ProtocolIEID = 72
const Asn1vIdRRCInactiveTransitionReportRequest ProtocolIEID = 91
const Asn1vIdSecurityKey ProtocolIEID = 94
const Asn1vIdTraceActivation ProtocolIEID = 108
const Asn1vIdUERadioCapability ProtocolIEID = 117
const Asn1vIdUERadioCapabilityForPaging ProtocolIEID = 118
const Asn1vIdUESecurityCapabilities ProtocolIEID = 119
const Asn1vIdPDUSessionResourceFailedToSetupListCxtFail ProtocolIEID = 132
const Asn1vIdRedirectionVoiceFallback ProtocolIEID = 146
const Asn1vIdCNAssistedRANTuning ProtocolIEID = 165
const Asn1vIdLocationReportingAdditionalInfo ProtocolIEID = 170
