/*
 * Namf_Communication
 *
 * AMF Communication Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_commn_server

import "encoding/json"

type N1MessageClass struct {
	String *string
}

// type N1MessageClass string

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *N1MessageClass) UnmarshalJSON(data []byte) error {

	type Alias N1MessageClass // To avoid infinite recursion
	return json.Unmarshal(data, (*Alias)(m))
}

// AssertN1MessageClassRequired checks if the required fields are not zero-ed
func AssertN1MessageClassRequired(obj N1MessageClass) error {
	return nil
}

// AssertN1MessageClassConstraints checks if the values respects the defined constraints
func AssertN1MessageClassConstraints(obj N1MessageClass) error {
	return nil
}
