/*
 * Namf_Communication
 *
 * AMF Communication Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_commn_server

import (
	"encoding/json"
)

type AreaOfValidity struct {
	TaiList []Tai `json:"taiList"`
}

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *AreaOfValidity) UnmarshalJSON(data []byte) error {

	type Alias AreaOfValidity // To avoid infinite recursion
	return json.Unmarshal(data, (*Alias)(m))
}

// AssertAreaOfValidityRequired checks if the required fields are not zero-ed
func AssertAreaOfValidityRequired(obj AreaOfValidity) error {
	elements := map[string]interface{}{
		"taiList": obj.TaiList,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.TaiList {
		if err := AssertTaiRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertAreaOfValidityConstraints checks if the values respects the defined constraints
func AssertAreaOfValidityConstraints(obj AreaOfValidity) error {
	return nil
}
