/*
 * Namf_Communication
 *
 * AMF Communication Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_commn_server

import "encoding/json"

type N2InfoContainer struct {
	N2InformationClass N2InformationClass `json:"n2InformationClass"`

	SmInfo N2SmInformation `json:"smInfo,omitempty"`

	RanInfo N2RanInformation `json:"ranInfo,omitempty"`

	NrppaInfo NrppaInformation `json:"nrppaInfo,omitempty"`

	PwsInfo PwsInformation `json:"pwsInfo,omitempty"`
}

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *N2InfoContainer) UnmarshalJSON(data []byte) error {

	type Alias N2InfoContainer // To avoid infinite recursion
	return json.Unmarshal(data, (*Alias)(m))
}

// AssertN2InfoContainerRequired checks if the required fields are not zero-ed
func AssertN2InfoContainerRequired(obj N2InfoContainer) error {
	elements := map[string]interface{}{
		"n2InformationClass": obj.N2InformationClass,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertN2InformationClassRequired(obj.N2InformationClass); err != nil {
		return err
	}
	if err := AssertN2SmInformationRequired(obj.SmInfo); err != nil {
		return err
	}
	// if err := AssertN2RanInformationRequired(obj.RanInfo); err != nil {
	// 	return err
	// }
	// if err := AssertNrppaInformationRequired(obj.NrppaInfo); err != nil {
	// 	return err
	// }
	// if err := AssertPwsInformationRequired(obj.PwsInfo); err != nil {
	// 	return err
	// }
	return nil
}

// AssertN2InfoContainerConstraints checks if the values respects the defined constraints
func AssertN2InfoContainerConstraints(obj N2InfoContainer) error {
	return nil
}
