/*
Namf_Communication

AMF Communication Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

API version: 1.0.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_commn_client

import (
	"encoding/json"
)

// checks if the NsiInformation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NsiInformation{}

// NsiInformation struct for NsiInformation
type NsiInformation struct {
	NrfId string `json:"nrfId"`
	NsiId *string `json:"nsiId,omitempty"`
	NrfNfMgtUri *string `json:"nrfNfMgtUri,omitempty"`
	NrfAccessTokenUri *string `json:"nrfAccessTokenUri,omitempty"`
}

// NewNsiInformation instantiates a new NsiInformation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNsiInformation(nrfId string) *NsiInformation {
	this := NsiInformation{}
	this.NrfId = nrfId
	return &this
}

// NewNsiInformationWithDefaults instantiates a new NsiInformation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNsiInformationWithDefaults() *NsiInformation {
	this := NsiInformation{}
	return &this
}

// GetNrfId returns the NrfId field value
func (o *NsiInformation) GetNrfId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NrfId
}

// GetNrfIdOk returns a tuple with the NrfId field value
// and a boolean to check if the value has been set.
func (o *NsiInformation) GetNrfIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NrfId, true
}

// SetNrfId sets field value
func (o *NsiInformation) SetNrfId(v string) {
	o.NrfId = v
}

// GetNsiId returns the NsiId field value if set, zero value otherwise.
func (o *NsiInformation) GetNsiId() string {
	if o == nil || IsNil(o.NsiId) {
		var ret string
		return ret
	}
	return *o.NsiId
}

// GetNsiIdOk returns a tuple with the NsiId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NsiInformation) GetNsiIdOk() (*string, bool) {
	if o == nil || IsNil(o.NsiId) {
		return nil, false
	}
	return o.NsiId, true
}

// HasNsiId returns a boolean if a field has been set.
func (o *NsiInformation) HasNsiId() bool {
	if o != nil && !IsNil(o.NsiId) {
		return true
	}

	return false
}

// SetNsiId gets a reference to the given string and assigns it to the NsiId field.
func (o *NsiInformation) SetNsiId(v string) {
	o.NsiId = &v
}

// GetNrfNfMgtUri returns the NrfNfMgtUri field value if set, zero value otherwise.
func (o *NsiInformation) GetNrfNfMgtUri() string {
	if o == nil || IsNil(o.NrfNfMgtUri) {
		var ret string
		return ret
	}
	return *o.NrfNfMgtUri
}

// GetNrfNfMgtUriOk returns a tuple with the NrfNfMgtUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NsiInformation) GetNrfNfMgtUriOk() (*string, bool) {
	if o == nil || IsNil(o.NrfNfMgtUri) {
		return nil, false
	}
	return o.NrfNfMgtUri, true
}

// HasNrfNfMgtUri returns a boolean if a field has been set.
func (o *NsiInformation) HasNrfNfMgtUri() bool {
	if o != nil && !IsNil(o.NrfNfMgtUri) {
		return true
	}

	return false
}

// SetNrfNfMgtUri gets a reference to the given string and assigns it to the NrfNfMgtUri field.
func (o *NsiInformation) SetNrfNfMgtUri(v string) {
	o.NrfNfMgtUri = &v
}

// GetNrfAccessTokenUri returns the NrfAccessTokenUri field value if set, zero value otherwise.
func (o *NsiInformation) GetNrfAccessTokenUri() string {
	if o == nil || IsNil(o.NrfAccessTokenUri) {
		var ret string
		return ret
	}
	return *o.NrfAccessTokenUri
}

// GetNrfAccessTokenUriOk returns a tuple with the NrfAccessTokenUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NsiInformation) GetNrfAccessTokenUriOk() (*string, bool) {
	if o == nil || IsNil(o.NrfAccessTokenUri) {
		return nil, false
	}
	return o.NrfAccessTokenUri, true
}

// HasNrfAccessTokenUri returns a boolean if a field has been set.
func (o *NsiInformation) HasNrfAccessTokenUri() bool {
	if o != nil && !IsNil(o.NrfAccessTokenUri) {
		return true
	}

	return false
}

// SetNrfAccessTokenUri gets a reference to the given string and assigns it to the NrfAccessTokenUri field.
func (o *NsiInformation) SetNrfAccessTokenUri(v string) {
	o.NrfAccessTokenUri = &v
}

func (o NsiInformation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NsiInformation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["nrfId"] = o.NrfId
	if !IsNil(o.NsiId) {
		toSerialize["nsiId"] = o.NsiId
	}
	if !IsNil(o.NrfNfMgtUri) {
		toSerialize["nrfNfMgtUri"] = o.NrfNfMgtUri
	}
	if !IsNil(o.NrfAccessTokenUri) {
		toSerialize["nrfAccessTokenUri"] = o.NrfAccessTokenUri
	}
	return toSerialize, nil
}

type NullableNsiInformation struct {
	value *NsiInformation
	isSet bool
}

func (v NullableNsiInformation) Get() *NsiInformation {
	return v.value
}

func (v *NullableNsiInformation) Set(val *NsiInformation) {
	v.value = val
	v.isSet = true
}

func (v NullableNsiInformation) IsSet() bool {
	return v.isSet
}

func (v *NullableNsiInformation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNsiInformation(val *NsiInformation) *NullableNsiInformation {
	return &NullableNsiInformation{value: val, isSet: true}
}

func (v NullableNsiInformation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNsiInformation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


