/*
Namf_Communication

AMF Communication Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

API version: 1.0.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_commn_client

import (
	"encoding/json"
)

// checks if the PduSessionContext type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PduSessionContext{}

// PduSessionContext struct for PduSessionContext
type PduSessionContext struct {
	PduSessionId int32 `json:"pduSessionId"`
	SmContextRef string `json:"smContextRef"`
	SNssai Snssai `json:"sNssai"`
	Dnn string `json:"dnn"`
	AccessType AccessType `json:"accessType"`
	AllocatedEbiList []EbiArpMapping `json:"allocatedEbiList,omitempty"`
	HsmfId *string `json:"hsmfId,omitempty"`
	VsmfId *string `json:"vsmfId,omitempty"`
	NsInstance *string `json:"nsInstance,omitempty"`
	SmfServiceInstanceId *string `json:"smfServiceInstanceId,omitempty"`
}

// NewPduSessionContext instantiates a new PduSessionContext object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPduSessionContext(pduSessionId int32, smContextRef string, sNssai Snssai, dnn string, accessType AccessType) *PduSessionContext {
	this := PduSessionContext{}
	this.PduSessionId = pduSessionId
	this.SmContextRef = smContextRef
	this.SNssai = sNssai
	this.Dnn = dnn
	this.AccessType = accessType
	return &this
}

// NewPduSessionContextWithDefaults instantiates a new PduSessionContext object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPduSessionContextWithDefaults() *PduSessionContext {
	this := PduSessionContext{}
	return &this
}

// GetPduSessionId returns the PduSessionId field value
func (o *PduSessionContext) GetPduSessionId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PduSessionId
}

// GetPduSessionIdOk returns a tuple with the PduSessionId field value
// and a boolean to check if the value has been set.
func (o *PduSessionContext) GetPduSessionIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PduSessionId, true
}

// SetPduSessionId sets field value
func (o *PduSessionContext) SetPduSessionId(v int32) {
	o.PduSessionId = v
}

// GetSmContextRef returns the SmContextRef field value
func (o *PduSessionContext) GetSmContextRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SmContextRef
}

// GetSmContextRefOk returns a tuple with the SmContextRef field value
// and a boolean to check if the value has been set.
func (o *PduSessionContext) GetSmContextRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SmContextRef, true
}

// SetSmContextRef sets field value
func (o *PduSessionContext) SetSmContextRef(v string) {
	o.SmContextRef = v
}

// GetSNssai returns the SNssai field value
func (o *PduSessionContext) GetSNssai() Snssai {
	if o == nil {
		var ret Snssai
		return ret
	}

	return o.SNssai
}

// GetSNssaiOk returns a tuple with the SNssai field value
// and a boolean to check if the value has been set.
func (o *PduSessionContext) GetSNssaiOk() (*Snssai, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SNssai, true
}

// SetSNssai sets field value
func (o *PduSessionContext) SetSNssai(v Snssai) {
	o.SNssai = v
}

// GetDnn returns the Dnn field value
func (o *PduSessionContext) GetDnn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Dnn
}

// GetDnnOk returns a tuple with the Dnn field value
// and a boolean to check if the value has been set.
func (o *PduSessionContext) GetDnnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dnn, true
}

// SetDnn sets field value
func (o *PduSessionContext) SetDnn(v string) {
	o.Dnn = v
}

// GetAccessType returns the AccessType field value
func (o *PduSessionContext) GetAccessType() AccessType {
	if o == nil {
		var ret AccessType
		return ret
	}

	return o.AccessType
}

// GetAccessTypeOk returns a tuple with the AccessType field value
// and a boolean to check if the value has been set.
func (o *PduSessionContext) GetAccessTypeOk() (*AccessType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessType, true
}

// SetAccessType sets field value
func (o *PduSessionContext) SetAccessType(v AccessType) {
	o.AccessType = v
}

// GetAllocatedEbiList returns the AllocatedEbiList field value if set, zero value otherwise.
func (o *PduSessionContext) GetAllocatedEbiList() []EbiArpMapping {
	if o == nil || IsNil(o.AllocatedEbiList) {
		var ret []EbiArpMapping
		return ret
	}
	return o.AllocatedEbiList
}

// GetAllocatedEbiListOk returns a tuple with the AllocatedEbiList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionContext) GetAllocatedEbiListOk() ([]EbiArpMapping, bool) {
	if o == nil || IsNil(o.AllocatedEbiList) {
		return nil, false
	}
	return o.AllocatedEbiList, true
}

// HasAllocatedEbiList returns a boolean if a field has been set.
func (o *PduSessionContext) HasAllocatedEbiList() bool {
	if o != nil && !IsNil(o.AllocatedEbiList) {
		return true
	}

	return false
}

// SetAllocatedEbiList gets a reference to the given []EbiArpMapping and assigns it to the AllocatedEbiList field.
func (o *PduSessionContext) SetAllocatedEbiList(v []EbiArpMapping) {
	o.AllocatedEbiList = v
}

// GetHsmfId returns the HsmfId field value if set, zero value otherwise.
func (o *PduSessionContext) GetHsmfId() string {
	if o == nil || IsNil(o.HsmfId) {
		var ret string
		return ret
	}
	return *o.HsmfId
}

// GetHsmfIdOk returns a tuple with the HsmfId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionContext) GetHsmfIdOk() (*string, bool) {
	if o == nil || IsNil(o.HsmfId) {
		return nil, false
	}
	return o.HsmfId, true
}

// HasHsmfId returns a boolean if a field has been set.
func (o *PduSessionContext) HasHsmfId() bool {
	if o != nil && !IsNil(o.HsmfId) {
		return true
	}

	return false
}

// SetHsmfId gets a reference to the given string and assigns it to the HsmfId field.
func (o *PduSessionContext) SetHsmfId(v string) {
	o.HsmfId = &v
}

// GetVsmfId returns the VsmfId field value if set, zero value otherwise.
func (o *PduSessionContext) GetVsmfId() string {
	if o == nil || IsNil(o.VsmfId) {
		var ret string
		return ret
	}
	return *o.VsmfId
}

// GetVsmfIdOk returns a tuple with the VsmfId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionContext) GetVsmfIdOk() (*string, bool) {
	if o == nil || IsNil(o.VsmfId) {
		return nil, false
	}
	return o.VsmfId, true
}

// HasVsmfId returns a boolean if a field has been set.
func (o *PduSessionContext) HasVsmfId() bool {
	if o != nil && !IsNil(o.VsmfId) {
		return true
	}

	return false
}

// SetVsmfId gets a reference to the given string and assigns it to the VsmfId field.
func (o *PduSessionContext) SetVsmfId(v string) {
	o.VsmfId = &v
}

// GetNsInstance returns the NsInstance field value if set, zero value otherwise.
func (o *PduSessionContext) GetNsInstance() string {
	if o == nil || IsNil(o.NsInstance) {
		var ret string
		return ret
	}
	return *o.NsInstance
}

// GetNsInstanceOk returns a tuple with the NsInstance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionContext) GetNsInstanceOk() (*string, bool) {
	if o == nil || IsNil(o.NsInstance) {
		return nil, false
	}
	return o.NsInstance, true
}

// HasNsInstance returns a boolean if a field has been set.
func (o *PduSessionContext) HasNsInstance() bool {
	if o != nil && !IsNil(o.NsInstance) {
		return true
	}

	return false
}

// SetNsInstance gets a reference to the given string and assigns it to the NsInstance field.
func (o *PduSessionContext) SetNsInstance(v string) {
	o.NsInstance = &v
}

// GetSmfServiceInstanceId returns the SmfServiceInstanceId field value if set, zero value otherwise.
func (o *PduSessionContext) GetSmfServiceInstanceId() string {
	if o == nil || IsNil(o.SmfServiceInstanceId) {
		var ret string
		return ret
	}
	return *o.SmfServiceInstanceId
}

// GetSmfServiceInstanceIdOk returns a tuple with the SmfServiceInstanceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionContext) GetSmfServiceInstanceIdOk() (*string, bool) {
	if o == nil || IsNil(o.SmfServiceInstanceId) {
		return nil, false
	}
	return o.SmfServiceInstanceId, true
}

// HasSmfServiceInstanceId returns a boolean if a field has been set.
func (o *PduSessionContext) HasSmfServiceInstanceId() bool {
	if o != nil && !IsNil(o.SmfServiceInstanceId) {
		return true
	}

	return false
}

// SetSmfServiceInstanceId gets a reference to the given string and assigns it to the SmfServiceInstanceId field.
func (o *PduSessionContext) SetSmfServiceInstanceId(v string) {
	o.SmfServiceInstanceId = &v
}

func (o PduSessionContext) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PduSessionContext) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pduSessionId"] = o.PduSessionId
	toSerialize["smContextRef"] = o.SmContextRef
	toSerialize["sNssai"] = o.SNssai
	toSerialize["dnn"] = o.Dnn
	toSerialize["accessType"] = o.AccessType
	if !IsNil(o.AllocatedEbiList) {
		toSerialize["allocatedEbiList"] = o.AllocatedEbiList
	}
	if !IsNil(o.HsmfId) {
		toSerialize["hsmfId"] = o.HsmfId
	}
	if !IsNil(o.VsmfId) {
		toSerialize["vsmfId"] = o.VsmfId
	}
	if !IsNil(o.NsInstance) {
		toSerialize["nsInstance"] = o.NsInstance
	}
	if !IsNil(o.SmfServiceInstanceId) {
		toSerialize["smfServiceInstanceId"] = o.SmfServiceInstanceId
	}
	return toSerialize, nil
}

type NullablePduSessionContext struct {
	value *PduSessionContext
	isSet bool
}

func (v NullablePduSessionContext) Get() *PduSessionContext {
	return v.value
}

func (v *NullablePduSessionContext) Set(val *PduSessionContext) {
	v.value = val
	v.isSet = true
}

func (v NullablePduSessionContext) IsSet() bool {
	return v.isSet
}

func (v *NullablePduSessionContext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePduSessionContext(val *PduSessionContext) *NullablePduSessionContext {
	return &NullablePduSessionContext{value: val, isSet: true}
}

func (v NullablePduSessionContext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePduSessionContext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


