/*
Nsmf_PDUSession

SMF PDU Session Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

API version: 1.0.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
	"time"
)

// checks if the PduSessionCreateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PduSessionCreateData{}

// PduSessionCreateData struct for PduSessionCreateData
type PduSessionCreateData struct {
	Supi *string `json:"supi,omitempty"`
	UnauthenticatedSupi *bool `json:"unauthenticatedSupi,omitempty"`
	Pei *string `json:"pei,omitempty"`
	PduSessionId *int32 `json:"pduSessionId,omitempty"`
	Dnn string `json:"dnn"`
	SNssai *Snssai `json:"sNssai,omitempty"`
	VsmfId string `json:"vsmfId"`
	ServingNetwork PlmnId `json:"servingNetwork"`
	RequestType *RequestType `json:"requestType,omitempty"`
	EpsBearerId []int32 `json:"epsBearerId,omitempty"`
	PgwS8cFteid *string `json:"pgwS8cFteid,omitempty"`
	VsmfPduSessionUri string `json:"vsmfPduSessionUri"`
	VcnTunnelInfo TunnelInfo `json:"vcnTunnelInfo"`
	AnType AccessType `json:"anType"`
	RatType *RatType `json:"ratType,omitempty"`
	UeLocation *UserLocation `json:"ueLocation,omitempty"`
	UeTimeZone *string `json:"ueTimeZone,omitempty"`
	AddUeLocation *UserLocation `json:"addUeLocation,omitempty"`
	Gpsi *string `json:"gpsi,omitempty"`
	N1SmInfoFromUe *RefToBinaryData `json:"n1SmInfoFromUe,omitempty"`
	UnknownN1SmInfo *RefToBinaryData `json:"unknownN1SmInfo,omitempty"`
	SupportedFeatures *string `json:"supportedFeatures,omitempty"`
	HPcfId *string `json:"hPcfId,omitempty"`
	HoPreparationIndication *bool `json:"hoPreparationIndication,omitempty"`
	SelMode *DnnSelectionMode `json:"selMode,omitempty"`
	AlwaysOnRequested *bool `json:"alwaysOnRequested,omitempty"`
	UdmGroupId *string `json:"udmGroupId,omitempty"`
	RoutingIndicator *string `json:"routingIndicator,omitempty"`
	EpsInterworkingInd *EpsInterworkingIndication `json:"epsInterworkingInd,omitempty"`
	VSmfServiceInstanceId *string `json:"vSmfServiceInstanceId,omitempty"`
	RecoveryTime *time.Time `json:"recoveryTime,omitempty"`
	RoamingChargingProfile *RoamingChargingProfile `json:"roamingChargingProfile,omitempty"`
	ChargingId *string `json:"chargingId,omitempty"`
	OldPduSessionId *int32 `json:"oldPduSessionId,omitempty"`
	EpsBearerCtxStatus *string `json:"epsBearerCtxStatus,omitempty"`
	AmfNfId *string `json:"amfNfId,omitempty"`
	Guami *Guami `json:"guami,omitempty"`
	MaxIntegrityProtectedDataRateUl *MaxIntegrityProtectedDataRate `json:"maxIntegrityProtectedDataRateUl,omitempty"`
	MaxIntegrityProtectedDataRateDl *MaxIntegrityProtectedDataRate `json:"maxIntegrityProtectedDataRateDl,omitempty"`
}

// NewPduSessionCreateData instantiates a new PduSessionCreateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPduSessionCreateData(dnn string, vsmfId string, servingNetwork PlmnId, vsmfPduSessionUri string, vcnTunnelInfo TunnelInfo, anType AccessType) *PduSessionCreateData {
	this := PduSessionCreateData{}
	var unauthenticatedSupi bool = false
	this.UnauthenticatedSupi = &unauthenticatedSupi
	this.Dnn = dnn
	this.VsmfId = vsmfId
	this.ServingNetwork = servingNetwork
	this.VsmfPduSessionUri = vsmfPduSessionUri
	this.VcnTunnelInfo = vcnTunnelInfo
	this.AnType = anType
	var alwaysOnRequested bool = false
	this.AlwaysOnRequested = &alwaysOnRequested
	return &this
}

// NewPduSessionCreateDataWithDefaults instantiates a new PduSessionCreateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPduSessionCreateDataWithDefaults() *PduSessionCreateData {
	this := PduSessionCreateData{}
	var unauthenticatedSupi bool = false
	this.UnauthenticatedSupi = &unauthenticatedSupi
	var alwaysOnRequested bool = false
	this.AlwaysOnRequested = &alwaysOnRequested
	return &this
}

// GetSupi returns the Supi field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetSupi() string {
	if o == nil || IsNil(o.Supi) {
		var ret string
		return ret
	}
	return *o.Supi
}

// GetSupiOk returns a tuple with the Supi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetSupiOk() (*string, bool) {
	if o == nil || IsNil(o.Supi) {
		return nil, false
	}
	return o.Supi, true
}

// HasSupi returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasSupi() bool {
	if o != nil && !IsNil(o.Supi) {
		return true
	}

	return false
}

// SetSupi gets a reference to the given string and assigns it to the Supi field.
func (o *PduSessionCreateData) SetSupi(v string) {
	o.Supi = &v
}

// GetUnauthenticatedSupi returns the UnauthenticatedSupi field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetUnauthenticatedSupi() bool {
	if o == nil || IsNil(o.UnauthenticatedSupi) {
		var ret bool
		return ret
	}
	return *o.UnauthenticatedSupi
}

// GetUnauthenticatedSupiOk returns a tuple with the UnauthenticatedSupi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetUnauthenticatedSupiOk() (*bool, bool) {
	if o == nil || IsNil(o.UnauthenticatedSupi) {
		return nil, false
	}
	return o.UnauthenticatedSupi, true
}

// HasUnauthenticatedSupi returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasUnauthenticatedSupi() bool {
	if o != nil && !IsNil(o.UnauthenticatedSupi) {
		return true
	}

	return false
}

// SetUnauthenticatedSupi gets a reference to the given bool and assigns it to the UnauthenticatedSupi field.
func (o *PduSessionCreateData) SetUnauthenticatedSupi(v bool) {
	o.UnauthenticatedSupi = &v
}

// GetPei returns the Pei field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetPei() string {
	if o == nil || IsNil(o.Pei) {
		var ret string
		return ret
	}
	return *o.Pei
}

// GetPeiOk returns a tuple with the Pei field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetPeiOk() (*string, bool) {
	if o == nil || IsNil(o.Pei) {
		return nil, false
	}
	return o.Pei, true
}

// HasPei returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasPei() bool {
	if o != nil && !IsNil(o.Pei) {
		return true
	}

	return false
}

// SetPei gets a reference to the given string and assigns it to the Pei field.
func (o *PduSessionCreateData) SetPei(v string) {
	o.Pei = &v
}

// GetPduSessionId returns the PduSessionId field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetPduSessionId() int32 {
	if o == nil || IsNil(o.PduSessionId) {
		var ret int32
		return ret
	}
	return *o.PduSessionId
}

// GetPduSessionIdOk returns a tuple with the PduSessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetPduSessionIdOk() (*int32, bool) {
	if o == nil || IsNil(o.PduSessionId) {
		return nil, false
	}
	return o.PduSessionId, true
}

// HasPduSessionId returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasPduSessionId() bool {
	if o != nil && !IsNil(o.PduSessionId) {
		return true
	}

	return false
}

// SetPduSessionId gets a reference to the given int32 and assigns it to the PduSessionId field.
func (o *PduSessionCreateData) SetPduSessionId(v int32) {
	o.PduSessionId = &v
}

// GetDnn returns the Dnn field value
func (o *PduSessionCreateData) GetDnn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Dnn
}

// GetDnnOk returns a tuple with the Dnn field value
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetDnnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dnn, true
}

// SetDnn sets field value
func (o *PduSessionCreateData) SetDnn(v string) {
	o.Dnn = v
}

// GetSNssai returns the SNssai field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetSNssai() Snssai {
	if o == nil || IsNil(o.SNssai) {
		var ret Snssai
		return ret
	}
	return *o.SNssai
}

// GetSNssaiOk returns a tuple with the SNssai field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetSNssaiOk() (*Snssai, bool) {
	if o == nil || IsNil(o.SNssai) {
		return nil, false
	}
	return o.SNssai, true
}

// HasSNssai returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasSNssai() bool {
	if o != nil && !IsNil(o.SNssai) {
		return true
	}

	return false
}

// SetSNssai gets a reference to the given Snssai and assigns it to the SNssai field.
func (o *PduSessionCreateData) SetSNssai(v Snssai) {
	o.SNssai = &v
}

// GetVsmfId returns the VsmfId field value
func (o *PduSessionCreateData) GetVsmfId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VsmfId
}

// GetVsmfIdOk returns a tuple with the VsmfId field value
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetVsmfIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VsmfId, true
}

// SetVsmfId sets field value
func (o *PduSessionCreateData) SetVsmfId(v string) {
	o.VsmfId = v
}

// GetServingNetwork returns the ServingNetwork field value
func (o *PduSessionCreateData) GetServingNetwork() PlmnId {
	if o == nil {
		var ret PlmnId
		return ret
	}

	return o.ServingNetwork
}

// GetServingNetworkOk returns a tuple with the ServingNetwork field value
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetServingNetworkOk() (*PlmnId, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServingNetwork, true
}

// SetServingNetwork sets field value
func (o *PduSessionCreateData) SetServingNetwork(v PlmnId) {
	o.ServingNetwork = v
}

// GetRequestType returns the RequestType field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetRequestType() RequestType {
	if o == nil || IsNil(o.RequestType) {
		var ret RequestType
		return ret
	}
	return *o.RequestType
}

// GetRequestTypeOk returns a tuple with the RequestType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetRequestTypeOk() (*RequestType, bool) {
	if o == nil || IsNil(o.RequestType) {
		return nil, false
	}
	return o.RequestType, true
}

// HasRequestType returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasRequestType() bool {
	if o != nil && !IsNil(o.RequestType) {
		return true
	}

	return false
}

// SetRequestType gets a reference to the given RequestType and assigns it to the RequestType field.
func (o *PduSessionCreateData) SetRequestType(v RequestType) {
	o.RequestType = &v
}

// GetEpsBearerId returns the EpsBearerId field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetEpsBearerId() []int32 {
	if o == nil || IsNil(o.EpsBearerId) {
		var ret []int32
		return ret
	}
	return o.EpsBearerId
}

// GetEpsBearerIdOk returns a tuple with the EpsBearerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetEpsBearerIdOk() ([]int32, bool) {
	if o == nil || IsNil(o.EpsBearerId) {
		return nil, false
	}
	return o.EpsBearerId, true
}

// HasEpsBearerId returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasEpsBearerId() bool {
	if o != nil && !IsNil(o.EpsBearerId) {
		return true
	}

	return false
}

// SetEpsBearerId gets a reference to the given []int32 and assigns it to the EpsBearerId field.
func (o *PduSessionCreateData) SetEpsBearerId(v []int32) {
	o.EpsBearerId = v
}

// GetPgwS8cFteid returns the PgwS8cFteid field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetPgwS8cFteid() string {
	if o == nil || IsNil(o.PgwS8cFteid) {
		var ret string
		return ret
	}
	return *o.PgwS8cFteid
}

// GetPgwS8cFteidOk returns a tuple with the PgwS8cFteid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetPgwS8cFteidOk() (*string, bool) {
	if o == nil || IsNil(o.PgwS8cFteid) {
		return nil, false
	}
	return o.PgwS8cFteid, true
}

// HasPgwS8cFteid returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasPgwS8cFteid() bool {
	if o != nil && !IsNil(o.PgwS8cFteid) {
		return true
	}

	return false
}

// SetPgwS8cFteid gets a reference to the given string and assigns it to the PgwS8cFteid field.
func (o *PduSessionCreateData) SetPgwS8cFteid(v string) {
	o.PgwS8cFteid = &v
}

// GetVsmfPduSessionUri returns the VsmfPduSessionUri field value
func (o *PduSessionCreateData) GetVsmfPduSessionUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VsmfPduSessionUri
}

// GetVsmfPduSessionUriOk returns a tuple with the VsmfPduSessionUri field value
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetVsmfPduSessionUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VsmfPduSessionUri, true
}

// SetVsmfPduSessionUri sets field value
func (o *PduSessionCreateData) SetVsmfPduSessionUri(v string) {
	o.VsmfPduSessionUri = v
}

// GetVcnTunnelInfo returns the VcnTunnelInfo field value
func (o *PduSessionCreateData) GetVcnTunnelInfo() TunnelInfo {
	if o == nil {
		var ret TunnelInfo
		return ret
	}

	return o.VcnTunnelInfo
}

// GetVcnTunnelInfoOk returns a tuple with the VcnTunnelInfo field value
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetVcnTunnelInfoOk() (*TunnelInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VcnTunnelInfo, true
}

// SetVcnTunnelInfo sets field value
func (o *PduSessionCreateData) SetVcnTunnelInfo(v TunnelInfo) {
	o.VcnTunnelInfo = v
}

// GetAnType returns the AnType field value
func (o *PduSessionCreateData) GetAnType() AccessType {
	if o == nil {
		var ret AccessType
		return ret
	}

	return o.AnType
}

// GetAnTypeOk returns a tuple with the AnType field value
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetAnTypeOk() (*AccessType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AnType, true
}

// SetAnType sets field value
func (o *PduSessionCreateData) SetAnType(v AccessType) {
	o.AnType = v
}

// GetRatType returns the RatType field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetRatType() RatType {
	if o == nil || IsNil(o.RatType) {
		var ret RatType
		return ret
	}
	return *o.RatType
}

// GetRatTypeOk returns a tuple with the RatType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetRatTypeOk() (*RatType, bool) {
	if o == nil || IsNil(o.RatType) {
		return nil, false
	}
	return o.RatType, true
}

// HasRatType returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasRatType() bool {
	if o != nil && !IsNil(o.RatType) {
		return true
	}

	return false
}

// SetRatType gets a reference to the given RatType and assigns it to the RatType field.
func (o *PduSessionCreateData) SetRatType(v RatType) {
	o.RatType = &v
}

// GetUeLocation returns the UeLocation field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetUeLocation() UserLocation {
	if o == nil || IsNil(o.UeLocation) {
		var ret UserLocation
		return ret
	}
	return *o.UeLocation
}

// GetUeLocationOk returns a tuple with the UeLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetUeLocationOk() (*UserLocation, bool) {
	if o == nil || IsNil(o.UeLocation) {
		return nil, false
	}
	return o.UeLocation, true
}

// HasUeLocation returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasUeLocation() bool {
	if o != nil && !IsNil(o.UeLocation) {
		return true
	}

	return false
}

// SetUeLocation gets a reference to the given UserLocation and assigns it to the UeLocation field.
func (o *PduSessionCreateData) SetUeLocation(v UserLocation) {
	o.UeLocation = &v
}

// GetUeTimeZone returns the UeTimeZone field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetUeTimeZone() string {
	if o == nil || IsNil(o.UeTimeZone) {
		var ret string
		return ret
	}
	return *o.UeTimeZone
}

// GetUeTimeZoneOk returns a tuple with the UeTimeZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetUeTimeZoneOk() (*string, bool) {
	if o == nil || IsNil(o.UeTimeZone) {
		return nil, false
	}
	return o.UeTimeZone, true
}

// HasUeTimeZone returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasUeTimeZone() bool {
	if o != nil && !IsNil(o.UeTimeZone) {
		return true
	}

	return false
}

// SetUeTimeZone gets a reference to the given string and assigns it to the UeTimeZone field.
func (o *PduSessionCreateData) SetUeTimeZone(v string) {
	o.UeTimeZone = &v
}

// GetAddUeLocation returns the AddUeLocation field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetAddUeLocation() UserLocation {
	if o == nil || IsNil(o.AddUeLocation) {
		var ret UserLocation
		return ret
	}
	return *o.AddUeLocation
}

// GetAddUeLocationOk returns a tuple with the AddUeLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetAddUeLocationOk() (*UserLocation, bool) {
	if o == nil || IsNil(o.AddUeLocation) {
		return nil, false
	}
	return o.AddUeLocation, true
}

// HasAddUeLocation returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasAddUeLocation() bool {
	if o != nil && !IsNil(o.AddUeLocation) {
		return true
	}

	return false
}

// SetAddUeLocation gets a reference to the given UserLocation and assigns it to the AddUeLocation field.
func (o *PduSessionCreateData) SetAddUeLocation(v UserLocation) {
	o.AddUeLocation = &v
}

// GetGpsi returns the Gpsi field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetGpsi() string {
	if o == nil || IsNil(o.Gpsi) {
		var ret string
		return ret
	}
	return *o.Gpsi
}

// GetGpsiOk returns a tuple with the Gpsi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetGpsiOk() (*string, bool) {
	if o == nil || IsNil(o.Gpsi) {
		return nil, false
	}
	return o.Gpsi, true
}

// HasGpsi returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasGpsi() bool {
	if o != nil && !IsNil(o.Gpsi) {
		return true
	}

	return false
}

// SetGpsi gets a reference to the given string and assigns it to the Gpsi field.
func (o *PduSessionCreateData) SetGpsi(v string) {
	o.Gpsi = &v
}

// GetN1SmInfoFromUe returns the N1SmInfoFromUe field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetN1SmInfoFromUe() RefToBinaryData {
	if o == nil || IsNil(o.N1SmInfoFromUe) {
		var ret RefToBinaryData
		return ret
	}
	return *o.N1SmInfoFromUe
}

// GetN1SmInfoFromUeOk returns a tuple with the N1SmInfoFromUe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetN1SmInfoFromUeOk() (*RefToBinaryData, bool) {
	if o == nil || IsNil(o.N1SmInfoFromUe) {
		return nil, false
	}
	return o.N1SmInfoFromUe, true
}

// HasN1SmInfoFromUe returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasN1SmInfoFromUe() bool {
	if o != nil && !IsNil(o.N1SmInfoFromUe) {
		return true
	}

	return false
}

// SetN1SmInfoFromUe gets a reference to the given RefToBinaryData and assigns it to the N1SmInfoFromUe field.
func (o *PduSessionCreateData) SetN1SmInfoFromUe(v RefToBinaryData) {
	o.N1SmInfoFromUe = &v
}

// GetUnknownN1SmInfo returns the UnknownN1SmInfo field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetUnknownN1SmInfo() RefToBinaryData {
	if o == nil || IsNil(o.UnknownN1SmInfo) {
		var ret RefToBinaryData
		return ret
	}
	return *o.UnknownN1SmInfo
}

// GetUnknownN1SmInfoOk returns a tuple with the UnknownN1SmInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetUnknownN1SmInfoOk() (*RefToBinaryData, bool) {
	if o == nil || IsNil(o.UnknownN1SmInfo) {
		return nil, false
	}
	return o.UnknownN1SmInfo, true
}

// HasUnknownN1SmInfo returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasUnknownN1SmInfo() bool {
	if o != nil && !IsNil(o.UnknownN1SmInfo) {
		return true
	}

	return false
}

// SetUnknownN1SmInfo gets a reference to the given RefToBinaryData and assigns it to the UnknownN1SmInfo field.
func (o *PduSessionCreateData) SetUnknownN1SmInfo(v RefToBinaryData) {
	o.UnknownN1SmInfo = &v
}

// GetSupportedFeatures returns the SupportedFeatures field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetSupportedFeatures() string {
	if o == nil || IsNil(o.SupportedFeatures) {
		var ret string
		return ret
	}
	return *o.SupportedFeatures
}

// GetSupportedFeaturesOk returns a tuple with the SupportedFeatures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetSupportedFeaturesOk() (*string, bool) {
	if o == nil || IsNil(o.SupportedFeatures) {
		return nil, false
	}
	return o.SupportedFeatures, true
}

// HasSupportedFeatures returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasSupportedFeatures() bool {
	if o != nil && !IsNil(o.SupportedFeatures) {
		return true
	}

	return false
}

// SetSupportedFeatures gets a reference to the given string and assigns it to the SupportedFeatures field.
func (o *PduSessionCreateData) SetSupportedFeatures(v string) {
	o.SupportedFeatures = &v
}

// GetHPcfId returns the HPcfId field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetHPcfId() string {
	if o == nil || IsNil(o.HPcfId) {
		var ret string
		return ret
	}
	return *o.HPcfId
}

// GetHPcfIdOk returns a tuple with the HPcfId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetHPcfIdOk() (*string, bool) {
	if o == nil || IsNil(o.HPcfId) {
		return nil, false
	}
	return o.HPcfId, true
}

// HasHPcfId returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasHPcfId() bool {
	if o != nil && !IsNil(o.HPcfId) {
		return true
	}

	return false
}

// SetHPcfId gets a reference to the given string and assigns it to the HPcfId field.
func (o *PduSessionCreateData) SetHPcfId(v string) {
	o.HPcfId = &v
}

// GetHoPreparationIndication returns the HoPreparationIndication field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetHoPreparationIndication() bool {
	if o == nil || IsNil(o.HoPreparationIndication) {
		var ret bool
		return ret
	}
	return *o.HoPreparationIndication
}

// GetHoPreparationIndicationOk returns a tuple with the HoPreparationIndication field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetHoPreparationIndicationOk() (*bool, bool) {
	if o == nil || IsNil(o.HoPreparationIndication) {
		return nil, false
	}
	return o.HoPreparationIndication, true
}

// HasHoPreparationIndication returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasHoPreparationIndication() bool {
	if o != nil && !IsNil(o.HoPreparationIndication) {
		return true
	}

	return false
}

// SetHoPreparationIndication gets a reference to the given bool and assigns it to the HoPreparationIndication field.
func (o *PduSessionCreateData) SetHoPreparationIndication(v bool) {
	o.HoPreparationIndication = &v
}

// GetSelMode returns the SelMode field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetSelMode() DnnSelectionMode {
	if o == nil || IsNil(o.SelMode) {
		var ret DnnSelectionMode
		return ret
	}
	return *o.SelMode
}

// GetSelModeOk returns a tuple with the SelMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetSelModeOk() (*DnnSelectionMode, bool) {
	if o == nil || IsNil(o.SelMode) {
		return nil, false
	}
	return o.SelMode, true
}

// HasSelMode returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasSelMode() bool {
	if o != nil && !IsNil(o.SelMode) {
		return true
	}

	return false
}

// SetSelMode gets a reference to the given DnnSelectionMode and assigns it to the SelMode field.
func (o *PduSessionCreateData) SetSelMode(v DnnSelectionMode) {
	o.SelMode = &v
}

// GetAlwaysOnRequested returns the AlwaysOnRequested field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetAlwaysOnRequested() bool {
	if o == nil || IsNil(o.AlwaysOnRequested) {
		var ret bool
		return ret
	}
	return *o.AlwaysOnRequested
}

// GetAlwaysOnRequestedOk returns a tuple with the AlwaysOnRequested field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetAlwaysOnRequestedOk() (*bool, bool) {
	if o == nil || IsNil(o.AlwaysOnRequested) {
		return nil, false
	}
	return o.AlwaysOnRequested, true
}

// HasAlwaysOnRequested returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasAlwaysOnRequested() bool {
	if o != nil && !IsNil(o.AlwaysOnRequested) {
		return true
	}

	return false
}

// SetAlwaysOnRequested gets a reference to the given bool and assigns it to the AlwaysOnRequested field.
func (o *PduSessionCreateData) SetAlwaysOnRequested(v bool) {
	o.AlwaysOnRequested = &v
}

// GetUdmGroupId returns the UdmGroupId field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetUdmGroupId() string {
	if o == nil || IsNil(o.UdmGroupId) {
		var ret string
		return ret
	}
	return *o.UdmGroupId
}

// GetUdmGroupIdOk returns a tuple with the UdmGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetUdmGroupIdOk() (*string, bool) {
	if o == nil || IsNil(o.UdmGroupId) {
		return nil, false
	}
	return o.UdmGroupId, true
}

// HasUdmGroupId returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasUdmGroupId() bool {
	if o != nil && !IsNil(o.UdmGroupId) {
		return true
	}

	return false
}

// SetUdmGroupId gets a reference to the given string and assigns it to the UdmGroupId field.
func (o *PduSessionCreateData) SetUdmGroupId(v string) {
	o.UdmGroupId = &v
}

// GetRoutingIndicator returns the RoutingIndicator field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetRoutingIndicator() string {
	if o == nil || IsNil(o.RoutingIndicator) {
		var ret string
		return ret
	}
	return *o.RoutingIndicator
}

// GetRoutingIndicatorOk returns a tuple with the RoutingIndicator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetRoutingIndicatorOk() (*string, bool) {
	if o == nil || IsNil(o.RoutingIndicator) {
		return nil, false
	}
	return o.RoutingIndicator, true
}

// HasRoutingIndicator returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasRoutingIndicator() bool {
	if o != nil && !IsNil(o.RoutingIndicator) {
		return true
	}

	return false
}

// SetRoutingIndicator gets a reference to the given string and assigns it to the RoutingIndicator field.
func (o *PduSessionCreateData) SetRoutingIndicator(v string) {
	o.RoutingIndicator = &v
}

// GetEpsInterworkingInd returns the EpsInterworkingInd field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetEpsInterworkingInd() EpsInterworkingIndication {
	if o == nil || IsNil(o.EpsInterworkingInd) {
		var ret EpsInterworkingIndication
		return ret
	}
	return *o.EpsInterworkingInd
}

// GetEpsInterworkingIndOk returns a tuple with the EpsInterworkingInd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetEpsInterworkingIndOk() (*EpsInterworkingIndication, bool) {
	if o == nil || IsNil(o.EpsInterworkingInd) {
		return nil, false
	}
	return o.EpsInterworkingInd, true
}

// HasEpsInterworkingInd returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasEpsInterworkingInd() bool {
	if o != nil && !IsNil(o.EpsInterworkingInd) {
		return true
	}

	return false
}

// SetEpsInterworkingInd gets a reference to the given EpsInterworkingIndication and assigns it to the EpsInterworkingInd field.
func (o *PduSessionCreateData) SetEpsInterworkingInd(v EpsInterworkingIndication) {
	o.EpsInterworkingInd = &v
}

// GetVSmfServiceInstanceId returns the VSmfServiceInstanceId field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetVSmfServiceInstanceId() string {
	if o == nil || IsNil(o.VSmfServiceInstanceId) {
		var ret string
		return ret
	}
	return *o.VSmfServiceInstanceId
}

// GetVSmfServiceInstanceIdOk returns a tuple with the VSmfServiceInstanceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetVSmfServiceInstanceIdOk() (*string, bool) {
	if o == nil || IsNil(o.VSmfServiceInstanceId) {
		return nil, false
	}
	return o.VSmfServiceInstanceId, true
}

// HasVSmfServiceInstanceId returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasVSmfServiceInstanceId() bool {
	if o != nil && !IsNil(o.VSmfServiceInstanceId) {
		return true
	}

	return false
}

// SetVSmfServiceInstanceId gets a reference to the given string and assigns it to the VSmfServiceInstanceId field.
func (o *PduSessionCreateData) SetVSmfServiceInstanceId(v string) {
	o.VSmfServiceInstanceId = &v
}

// GetRecoveryTime returns the RecoveryTime field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetRecoveryTime() time.Time {
	if o == nil || IsNil(o.RecoveryTime) {
		var ret time.Time
		return ret
	}
	return *o.RecoveryTime
}

// GetRecoveryTimeOk returns a tuple with the RecoveryTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetRecoveryTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.RecoveryTime) {
		return nil, false
	}
	return o.RecoveryTime, true
}

// HasRecoveryTime returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasRecoveryTime() bool {
	if o != nil && !IsNil(o.RecoveryTime) {
		return true
	}

	return false
}

// SetRecoveryTime gets a reference to the given time.Time and assigns it to the RecoveryTime field.
func (o *PduSessionCreateData) SetRecoveryTime(v time.Time) {
	o.RecoveryTime = &v
}

// GetRoamingChargingProfile returns the RoamingChargingProfile field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetRoamingChargingProfile() RoamingChargingProfile {
	if o == nil || IsNil(o.RoamingChargingProfile) {
		var ret RoamingChargingProfile
		return ret
	}
	return *o.RoamingChargingProfile
}

// GetRoamingChargingProfileOk returns a tuple with the RoamingChargingProfile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetRoamingChargingProfileOk() (*RoamingChargingProfile, bool) {
	if o == nil || IsNil(o.RoamingChargingProfile) {
		return nil, false
	}
	return o.RoamingChargingProfile, true
}

// HasRoamingChargingProfile returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasRoamingChargingProfile() bool {
	if o != nil && !IsNil(o.RoamingChargingProfile) {
		return true
	}

	return false
}

// SetRoamingChargingProfile gets a reference to the given RoamingChargingProfile and assigns it to the RoamingChargingProfile field.
func (o *PduSessionCreateData) SetRoamingChargingProfile(v RoamingChargingProfile) {
	o.RoamingChargingProfile = &v
}

// GetChargingId returns the ChargingId field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetChargingId() string {
	if o == nil || IsNil(o.ChargingId) {
		var ret string
		return ret
	}
	return *o.ChargingId
}

// GetChargingIdOk returns a tuple with the ChargingId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetChargingIdOk() (*string, bool) {
	if o == nil || IsNil(o.ChargingId) {
		return nil, false
	}
	return o.ChargingId, true
}

// HasChargingId returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasChargingId() bool {
	if o != nil && !IsNil(o.ChargingId) {
		return true
	}

	return false
}

// SetChargingId gets a reference to the given string and assigns it to the ChargingId field.
func (o *PduSessionCreateData) SetChargingId(v string) {
	o.ChargingId = &v
}

// GetOldPduSessionId returns the OldPduSessionId field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetOldPduSessionId() int32 {
	if o == nil || IsNil(o.OldPduSessionId) {
		var ret int32
		return ret
	}
	return *o.OldPduSessionId
}

// GetOldPduSessionIdOk returns a tuple with the OldPduSessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetOldPduSessionIdOk() (*int32, bool) {
	if o == nil || IsNil(o.OldPduSessionId) {
		return nil, false
	}
	return o.OldPduSessionId, true
}

// HasOldPduSessionId returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasOldPduSessionId() bool {
	if o != nil && !IsNil(o.OldPduSessionId) {
		return true
	}

	return false
}

// SetOldPduSessionId gets a reference to the given int32 and assigns it to the OldPduSessionId field.
func (o *PduSessionCreateData) SetOldPduSessionId(v int32) {
	o.OldPduSessionId = &v
}

// GetEpsBearerCtxStatus returns the EpsBearerCtxStatus field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetEpsBearerCtxStatus() string {
	if o == nil || IsNil(o.EpsBearerCtxStatus) {
		var ret string
		return ret
	}
	return *o.EpsBearerCtxStatus
}

// GetEpsBearerCtxStatusOk returns a tuple with the EpsBearerCtxStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetEpsBearerCtxStatusOk() (*string, bool) {
	if o == nil || IsNil(o.EpsBearerCtxStatus) {
		return nil, false
	}
	return o.EpsBearerCtxStatus, true
}

// HasEpsBearerCtxStatus returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasEpsBearerCtxStatus() bool {
	if o != nil && !IsNil(o.EpsBearerCtxStatus) {
		return true
	}

	return false
}

// SetEpsBearerCtxStatus gets a reference to the given string and assigns it to the EpsBearerCtxStatus field.
func (o *PduSessionCreateData) SetEpsBearerCtxStatus(v string) {
	o.EpsBearerCtxStatus = &v
}

// GetAmfNfId returns the AmfNfId field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetAmfNfId() string {
	if o == nil || IsNil(o.AmfNfId) {
		var ret string
		return ret
	}
	return *o.AmfNfId
}

// GetAmfNfIdOk returns a tuple with the AmfNfId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetAmfNfIdOk() (*string, bool) {
	if o == nil || IsNil(o.AmfNfId) {
		return nil, false
	}
	return o.AmfNfId, true
}

// HasAmfNfId returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasAmfNfId() bool {
	if o != nil && !IsNil(o.AmfNfId) {
		return true
	}

	return false
}

// SetAmfNfId gets a reference to the given string and assigns it to the AmfNfId field.
func (o *PduSessionCreateData) SetAmfNfId(v string) {
	o.AmfNfId = &v
}

// GetGuami returns the Guami field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetGuami() Guami {
	if o == nil || IsNil(o.Guami) {
		var ret Guami
		return ret
	}
	return *o.Guami
}

// GetGuamiOk returns a tuple with the Guami field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetGuamiOk() (*Guami, bool) {
	if o == nil || IsNil(o.Guami) {
		return nil, false
	}
	return o.Guami, true
}

// HasGuami returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasGuami() bool {
	if o != nil && !IsNil(o.Guami) {
		return true
	}

	return false
}

// SetGuami gets a reference to the given Guami and assigns it to the Guami field.
func (o *PduSessionCreateData) SetGuami(v Guami) {
	o.Guami = &v
}

// GetMaxIntegrityProtectedDataRateUl returns the MaxIntegrityProtectedDataRateUl field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetMaxIntegrityProtectedDataRateUl() MaxIntegrityProtectedDataRate {
	if o == nil || IsNil(o.MaxIntegrityProtectedDataRateUl) {
		var ret MaxIntegrityProtectedDataRate
		return ret
	}
	return *o.MaxIntegrityProtectedDataRateUl
}

// GetMaxIntegrityProtectedDataRateUlOk returns a tuple with the MaxIntegrityProtectedDataRateUl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetMaxIntegrityProtectedDataRateUlOk() (*MaxIntegrityProtectedDataRate, bool) {
	if o == nil || IsNil(o.MaxIntegrityProtectedDataRateUl) {
		return nil, false
	}
	return o.MaxIntegrityProtectedDataRateUl, true
}

// HasMaxIntegrityProtectedDataRateUl returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasMaxIntegrityProtectedDataRateUl() bool {
	if o != nil && !IsNil(o.MaxIntegrityProtectedDataRateUl) {
		return true
	}

	return false
}

// SetMaxIntegrityProtectedDataRateUl gets a reference to the given MaxIntegrityProtectedDataRate and assigns it to the MaxIntegrityProtectedDataRateUl field.
func (o *PduSessionCreateData) SetMaxIntegrityProtectedDataRateUl(v MaxIntegrityProtectedDataRate) {
	o.MaxIntegrityProtectedDataRateUl = &v
}

// GetMaxIntegrityProtectedDataRateDl returns the MaxIntegrityProtectedDataRateDl field value if set, zero value otherwise.
func (o *PduSessionCreateData) GetMaxIntegrityProtectedDataRateDl() MaxIntegrityProtectedDataRate {
	if o == nil || IsNil(o.MaxIntegrityProtectedDataRateDl) {
		var ret MaxIntegrityProtectedDataRate
		return ret
	}
	return *o.MaxIntegrityProtectedDataRateDl
}

// GetMaxIntegrityProtectedDataRateDlOk returns a tuple with the MaxIntegrityProtectedDataRateDl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreateData) GetMaxIntegrityProtectedDataRateDlOk() (*MaxIntegrityProtectedDataRate, bool) {
	if o == nil || IsNil(o.MaxIntegrityProtectedDataRateDl) {
		return nil, false
	}
	return o.MaxIntegrityProtectedDataRateDl, true
}

// HasMaxIntegrityProtectedDataRateDl returns a boolean if a field has been set.
func (o *PduSessionCreateData) HasMaxIntegrityProtectedDataRateDl() bool {
	if o != nil && !IsNil(o.MaxIntegrityProtectedDataRateDl) {
		return true
	}

	return false
}

// SetMaxIntegrityProtectedDataRateDl gets a reference to the given MaxIntegrityProtectedDataRate and assigns it to the MaxIntegrityProtectedDataRateDl field.
func (o *PduSessionCreateData) SetMaxIntegrityProtectedDataRateDl(v MaxIntegrityProtectedDataRate) {
	o.MaxIntegrityProtectedDataRateDl = &v
}

func (o PduSessionCreateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PduSessionCreateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Supi) {
		toSerialize["supi"] = o.Supi
	}
	if !IsNil(o.UnauthenticatedSupi) {
		toSerialize["unauthenticatedSupi"] = o.UnauthenticatedSupi
	}
	if !IsNil(o.Pei) {
		toSerialize["pei"] = o.Pei
	}
	if !IsNil(o.PduSessionId) {
		toSerialize["pduSessionId"] = o.PduSessionId
	}
	toSerialize["dnn"] = o.Dnn
	if !IsNil(o.SNssai) {
		toSerialize["sNssai"] = o.SNssai
	}
	toSerialize["vsmfId"] = o.VsmfId
	toSerialize["servingNetwork"] = o.ServingNetwork
	if !IsNil(o.RequestType) {
		toSerialize["requestType"] = o.RequestType
	}
	if !IsNil(o.EpsBearerId) {
		toSerialize["epsBearerId"] = o.EpsBearerId
	}
	if !IsNil(o.PgwS8cFteid) {
		toSerialize["pgwS8cFteid"] = o.PgwS8cFteid
	}
	toSerialize["vsmfPduSessionUri"] = o.VsmfPduSessionUri
	toSerialize["vcnTunnelInfo"] = o.VcnTunnelInfo
	toSerialize["anType"] = o.AnType
	if !IsNil(o.RatType) {
		toSerialize["ratType"] = o.RatType
	}
	if !IsNil(o.UeLocation) {
		toSerialize["ueLocation"] = o.UeLocation
	}
	if !IsNil(o.UeTimeZone) {
		toSerialize["ueTimeZone"] = o.UeTimeZone
	}
	if !IsNil(o.AddUeLocation) {
		toSerialize["addUeLocation"] = o.AddUeLocation
	}
	if !IsNil(o.Gpsi) {
		toSerialize["gpsi"] = o.Gpsi
	}
	if !IsNil(o.N1SmInfoFromUe) {
		toSerialize["n1SmInfoFromUe"] = o.N1SmInfoFromUe
	}
	if !IsNil(o.UnknownN1SmInfo) {
		toSerialize["unknownN1SmInfo"] = o.UnknownN1SmInfo
	}
	if !IsNil(o.SupportedFeatures) {
		toSerialize["supportedFeatures"] = o.SupportedFeatures
	}
	if !IsNil(o.HPcfId) {
		toSerialize["hPcfId"] = o.HPcfId
	}
	if !IsNil(o.HoPreparationIndication) {
		toSerialize["hoPreparationIndication"] = o.HoPreparationIndication
	}
	if !IsNil(o.SelMode) {
		toSerialize["selMode"] = o.SelMode
	}
	if !IsNil(o.AlwaysOnRequested) {
		toSerialize["alwaysOnRequested"] = o.AlwaysOnRequested
	}
	if !IsNil(o.UdmGroupId) {
		toSerialize["udmGroupId"] = o.UdmGroupId
	}
	if !IsNil(o.RoutingIndicator) {
		toSerialize["routingIndicator"] = o.RoutingIndicator
	}
	if !IsNil(o.EpsInterworkingInd) {
		toSerialize["epsInterworkingInd"] = o.EpsInterworkingInd
	}
	if !IsNil(o.VSmfServiceInstanceId) {
		toSerialize["vSmfServiceInstanceId"] = o.VSmfServiceInstanceId
	}
	if !IsNil(o.RecoveryTime) {
		toSerialize["recoveryTime"] = o.RecoveryTime
	}
	if !IsNil(o.RoamingChargingProfile) {
		toSerialize["roamingChargingProfile"] = o.RoamingChargingProfile
	}
	if !IsNil(o.ChargingId) {
		toSerialize["chargingId"] = o.ChargingId
	}
	if !IsNil(o.OldPduSessionId) {
		toSerialize["oldPduSessionId"] = o.OldPduSessionId
	}
	if !IsNil(o.EpsBearerCtxStatus) {
		toSerialize["epsBearerCtxStatus"] = o.EpsBearerCtxStatus
	}
	if !IsNil(o.AmfNfId) {
		toSerialize["amfNfId"] = o.AmfNfId
	}
	if !IsNil(o.Guami) {
		toSerialize["guami"] = o.Guami
	}
	if !IsNil(o.MaxIntegrityProtectedDataRateUl) {
		toSerialize["maxIntegrityProtectedDataRateUl"] = o.MaxIntegrityProtectedDataRateUl
	}
	if !IsNil(o.MaxIntegrityProtectedDataRateDl) {
		toSerialize["maxIntegrityProtectedDataRateDl"] = o.MaxIntegrityProtectedDataRateDl
	}
	return toSerialize, nil
}

type NullablePduSessionCreateData struct {
	value *PduSessionCreateData
	isSet bool
}

func (v NullablePduSessionCreateData) Get() *PduSessionCreateData {
	return v.value
}

func (v *NullablePduSessionCreateData) Set(val *PduSessionCreateData) {
	v.value = val
	v.isSet = true
}

func (v NullablePduSessionCreateData) IsSet() bool {
	return v.isSet
}

func (v *NullablePduSessionCreateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePduSessionCreateData(val *PduSessionCreateData) *NullablePduSessionCreateData {
	return &NullablePduSessionCreateData{value: val, isSet: true}
}

func (v NullablePduSessionCreateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePduSessionCreateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


