/*
Nsmf_PDUSession

SMF PDU Session Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

API version: 1.0.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
	"os"
)

// checks if the ModifyPduSessionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModifyPduSessionRequest{}

// ModifyPduSessionRequest struct for ModifyPduSessionRequest
type ModifyPduSessionRequest struct {
	JsonData *VsmfUpdateData `json:"jsonData,omitempty"`
	BinaryDataN1SmInfoToUe **os.File `json:"binaryDataN1SmInfoToUe,omitempty"`
}

// NewModifyPduSessionRequest instantiates a new ModifyPduSessionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModifyPduSessionRequest() *ModifyPduSessionRequest {
	this := ModifyPduSessionRequest{}
	return &this
}

// NewModifyPduSessionRequestWithDefaults instantiates a new ModifyPduSessionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModifyPduSessionRequestWithDefaults() *ModifyPduSessionRequest {
	this := ModifyPduSessionRequest{}
	return &this
}

// GetJsonData returns the JsonData field value if set, zero value otherwise.
func (o *ModifyPduSessionRequest) GetJsonData() VsmfUpdateData {
	if o == nil || IsNil(o.JsonData) {
		var ret VsmfUpdateData
		return ret
	}
	return *o.JsonData
}

// GetJsonDataOk returns a tuple with the JsonData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModifyPduSessionRequest) GetJsonDataOk() (*VsmfUpdateData, bool) {
	if o == nil || IsNil(o.JsonData) {
		return nil, false
	}
	return o.JsonData, true
}

// HasJsonData returns a boolean if a field has been set.
func (o *ModifyPduSessionRequest) HasJsonData() bool {
	if o != nil && !IsNil(o.JsonData) {
		return true
	}

	return false
}

// SetJsonData gets a reference to the given VsmfUpdateData and assigns it to the JsonData field.
func (o *ModifyPduSessionRequest) SetJsonData(v VsmfUpdateData) {
	o.JsonData = &v
}

// GetBinaryDataN1SmInfoToUe returns the BinaryDataN1SmInfoToUe field value if set, zero value otherwise.
func (o *ModifyPduSessionRequest) GetBinaryDataN1SmInfoToUe() *os.File {
	if o == nil || IsNil(o.BinaryDataN1SmInfoToUe) {
		var ret *os.File
		return ret
	}
	return *o.BinaryDataN1SmInfoToUe
}

// GetBinaryDataN1SmInfoToUeOk returns a tuple with the BinaryDataN1SmInfoToUe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModifyPduSessionRequest) GetBinaryDataN1SmInfoToUeOk() (**os.File, bool) {
	if o == nil || IsNil(o.BinaryDataN1SmInfoToUe) {
		return nil, false
	}
	return o.BinaryDataN1SmInfoToUe, true
}

// HasBinaryDataN1SmInfoToUe returns a boolean if a field has been set.
func (o *ModifyPduSessionRequest) HasBinaryDataN1SmInfoToUe() bool {
	if o != nil && !IsNil(o.BinaryDataN1SmInfoToUe) {
		return true
	}

	return false
}

// SetBinaryDataN1SmInfoToUe gets a reference to the given *os.File and assigns it to the BinaryDataN1SmInfoToUe field.
func (o *ModifyPduSessionRequest) SetBinaryDataN1SmInfoToUe(v *os.File) {
	o.BinaryDataN1SmInfoToUe = &v
}

func (o ModifyPduSessionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModifyPduSessionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.JsonData) {
		toSerialize["jsonData"] = o.JsonData
	}
	if !IsNil(o.BinaryDataN1SmInfoToUe) {
		toSerialize["binaryDataN1SmInfoToUe"] = o.BinaryDataN1SmInfoToUe
	}
	return toSerialize, nil
}

type NullableModifyPduSessionRequest struct {
	value *ModifyPduSessionRequest
	isSet bool
}

func (v NullableModifyPduSessionRequest) Get() *ModifyPduSessionRequest {
	return v.value
}

func (v *NullableModifyPduSessionRequest) Set(val *ModifyPduSessionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModifyPduSessionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModifyPduSessionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModifyPduSessionRequest(val *ModifyPduSessionRequest) *NullableModifyPduSessionRequest {
	return &NullableModifyPduSessionRequest{value: val, isSet: true}
}

func (v NullableModifyPduSessionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModifyPduSessionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


