/*
Nsmf_PDUSession

SMF PDU Session Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

API version: 1.0.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
	"time"
)

// checks if the PduSessionCreatedData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PduSessionCreatedData{}

// PduSessionCreatedData struct for PduSessionCreatedData
type PduSessionCreatedData struct {
	PduSessionType PduSessionType `json:"pduSessionType"`
	SscMode string `json:"sscMode"`
	HcnTunnelInfo TunnelInfo `json:"hcnTunnelInfo"`
	SessionAmbr Ambr `json:"sessionAmbr"`
	QosFlowsSetupList []QosFlowSetupItem `json:"qosFlowsSetupList"`
	HSmfInstanceId string `json:"hSmfInstanceId"`
	PduSessionId *int32 `json:"pduSessionId,omitempty"`
	SNssai *Snssai `json:"sNssai,omitempty"`
	EnablePauseCharging *bool `json:"enablePauseCharging,omitempty"`
	UeIpv4Address *string `json:"ueIpv4Address,omitempty"`
	UeIpv6Prefix *Ipv6Prefix `json:"ueIpv6Prefix,omitempty"`
	N1SmInfoToUe *RefToBinaryData `json:"n1SmInfoToUe,omitempty"`
	EpsPdnCnxInfo *EpsPdnCnxInfo `json:"epsPdnCnxInfo,omitempty"`
	EpsBearerInfo []EpsBearerInfo `json:"epsBearerInfo,omitempty"`
	SupportedFeatures *string `json:"supportedFeatures,omitempty"`
	MaxIntegrityProtectedDataRate *MaxIntegrityProtectedDataRate `json:"maxIntegrityProtectedDataRate,omitempty"`
	MaxIntegrityProtectedDataRateDl *MaxIntegrityProtectedDataRate `json:"maxIntegrityProtectedDataRateDl,omitempty"`
	AlwaysOnGranted *bool `json:"alwaysOnGranted,omitempty"`
	Gpsi *string `json:"gpsi,omitempty"`
	UpSecurity *UpSecurity `json:"upSecurity,omitempty"`
	RoamingChargingProfile *RoamingChargingProfile `json:"roamingChargingProfile,omitempty"`
	HSmfServiceInstanceId *string `json:"hSmfServiceInstanceId,omitempty"`
	RecoveryTime *time.Time `json:"recoveryTime,omitempty"`
	UeIpv6InterfaceId *string `json:"ueIpv6InterfaceId,omitempty"`
}

// NewPduSessionCreatedData instantiates a new PduSessionCreatedData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPduSessionCreatedData(pduSessionType PduSessionType, sscMode string, hcnTunnelInfo TunnelInfo, sessionAmbr Ambr, qosFlowsSetupList []QosFlowSetupItem, hSmfInstanceId string) *PduSessionCreatedData {
	this := PduSessionCreatedData{}
	this.PduSessionType = pduSessionType
	this.SscMode = sscMode
	this.HcnTunnelInfo = hcnTunnelInfo
	this.SessionAmbr = sessionAmbr
	this.QosFlowsSetupList = qosFlowsSetupList
	this.HSmfInstanceId = hSmfInstanceId
	var enablePauseCharging bool = false
	this.EnablePauseCharging = &enablePauseCharging
	var alwaysOnGranted bool = false
	this.AlwaysOnGranted = &alwaysOnGranted
	return &this
}

// NewPduSessionCreatedDataWithDefaults instantiates a new PduSessionCreatedData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPduSessionCreatedDataWithDefaults() *PduSessionCreatedData {
	this := PduSessionCreatedData{}
	var enablePauseCharging bool = false
	this.EnablePauseCharging = &enablePauseCharging
	var alwaysOnGranted bool = false
	this.AlwaysOnGranted = &alwaysOnGranted
	return &this
}

// GetPduSessionType returns the PduSessionType field value
func (o *PduSessionCreatedData) GetPduSessionType() PduSessionType {
	if o == nil {
		var ret PduSessionType
		return ret
	}

	return o.PduSessionType
}

// GetPduSessionTypeOk returns a tuple with the PduSessionType field value
// and a boolean to check if the value has been set.
func (o *PduSessionCreatedData) GetPduSessionTypeOk() (*PduSessionType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PduSessionType, true
}

// SetPduSessionType sets field value
func (o *PduSessionCreatedData) SetPduSessionType(v PduSessionType) {
	o.PduSessionType = v
}

// GetSscMode returns the SscMode field value
func (o *PduSessionCreatedData) GetSscMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SscMode
}

// GetSscModeOk returns a tuple with the SscMode field value
// and a boolean to check if the value has been set.
func (o *PduSessionCreatedData) GetSscModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SscMode, true
}

// SetSscMode sets field value
func (o *PduSessionCreatedData) SetSscMode(v string) {
	o.SscMode = v
}

// GetHcnTunnelInfo returns the HcnTunnelInfo field value
func (o *PduSessionCreatedData) GetHcnTunnelInfo() TunnelInfo {
	if o == nil {
		var ret TunnelInfo
		return ret
	}

	return o.HcnTunnelInfo
}

// GetHcnTunnelInfoOk returns a tuple with the HcnTunnelInfo field value
// and a boolean to check if the value has been set.
func (o *PduSessionCreatedData) GetHcnTunnelInfoOk() (*TunnelInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HcnTunnelInfo, true
}

// SetHcnTunnelInfo sets field value
func (o *PduSessionCreatedData) SetHcnTunnelInfo(v TunnelInfo) {
	o.HcnTunnelInfo = v
}

// GetSessionAmbr returns the SessionAmbr field value
func (o *PduSessionCreatedData) GetSessionAmbr() Ambr {
	if o == nil {
		var ret Ambr
		return ret
	}

	return o.SessionAmbr
}

// GetSessionAmbrOk returns a tuple with the SessionAmbr field value
// and a boolean to check if the value has been set.
func (o *PduSessionCreatedData) GetSessionAmbrOk() (*Ambr, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionAmbr, true
}

// SetSessionAmbr sets field value
func (o *PduSessionCreatedData) SetSessionAmbr(v Ambr) {
	o.SessionAmbr = v
}

// GetQosFlowsSetupList returns the QosFlowsSetupList field value
func (o *PduSessionCreatedData) GetQosFlowsSetupList() []QosFlowSetupItem {
	if o == nil {
		var ret []QosFlowSetupItem
		return ret
	}

	return o.QosFlowsSetupList
}

// GetQosFlowsSetupListOk returns a tuple with the QosFlowsSetupList field value
// and a boolean to check if the value has been set.
func (o *PduSessionCreatedData) GetQosFlowsSetupListOk() ([]QosFlowSetupItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.QosFlowsSetupList, true
}

// SetQosFlowsSetupList sets field value
func (o *PduSessionCreatedData) SetQosFlowsSetupList(v []QosFlowSetupItem) {
	o.QosFlowsSetupList = v
}

// GetHSmfInstanceId returns the HSmfInstanceId field value
func (o *PduSessionCreatedData) GetHSmfInstanceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HSmfInstanceId
}

// GetHSmfInstanceIdOk returns a tuple with the HSmfInstanceId field value
// and a boolean to check if the value has been set.
func (o *PduSessionCreatedData) GetHSmfInstanceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HSmfInstanceId, true
}

// SetHSmfInstanceId sets field value
func (o *PduSessionCreatedData) SetHSmfInstanceId(v string) {
	o.HSmfInstanceId = v
}

// GetPduSessionId returns the PduSessionId field value if set, zero value otherwise.
func (o *PduSessionCreatedData) GetPduSessionId() int32 {
	if o == nil || IsNil(o.PduSessionId) {
		var ret int32
		return ret
	}
	return *o.PduSessionId
}

// GetPduSessionIdOk returns a tuple with the PduSessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreatedData) GetPduSessionIdOk() (*int32, bool) {
	if o == nil || IsNil(o.PduSessionId) {
		return nil, false
	}
	return o.PduSessionId, true
}

// HasPduSessionId returns a boolean if a field has been set.
func (o *PduSessionCreatedData) HasPduSessionId() bool {
	if o != nil && !IsNil(o.PduSessionId) {
		return true
	}

	return false
}

// SetPduSessionId gets a reference to the given int32 and assigns it to the PduSessionId field.
func (o *PduSessionCreatedData) SetPduSessionId(v int32) {
	o.PduSessionId = &v
}

// GetSNssai returns the SNssai field value if set, zero value otherwise.
func (o *PduSessionCreatedData) GetSNssai() Snssai {
	if o == nil || IsNil(o.SNssai) {
		var ret Snssai
		return ret
	}
	return *o.SNssai
}

// GetSNssaiOk returns a tuple with the SNssai field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreatedData) GetSNssaiOk() (*Snssai, bool) {
	if o == nil || IsNil(o.SNssai) {
		return nil, false
	}
	return o.SNssai, true
}

// HasSNssai returns a boolean if a field has been set.
func (o *PduSessionCreatedData) HasSNssai() bool {
	if o != nil && !IsNil(o.SNssai) {
		return true
	}

	return false
}

// SetSNssai gets a reference to the given Snssai and assigns it to the SNssai field.
func (o *PduSessionCreatedData) SetSNssai(v Snssai) {
	o.SNssai = &v
}

// GetEnablePauseCharging returns the EnablePauseCharging field value if set, zero value otherwise.
func (o *PduSessionCreatedData) GetEnablePauseCharging() bool {
	if o == nil || IsNil(o.EnablePauseCharging) {
		var ret bool
		return ret
	}
	return *o.EnablePauseCharging
}

// GetEnablePauseChargingOk returns a tuple with the EnablePauseCharging field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreatedData) GetEnablePauseChargingOk() (*bool, bool) {
	if o == nil || IsNil(o.EnablePauseCharging) {
		return nil, false
	}
	return o.EnablePauseCharging, true
}

// HasEnablePauseCharging returns a boolean if a field has been set.
func (o *PduSessionCreatedData) HasEnablePauseCharging() bool {
	if o != nil && !IsNil(o.EnablePauseCharging) {
		return true
	}

	return false
}

// SetEnablePauseCharging gets a reference to the given bool and assigns it to the EnablePauseCharging field.
func (o *PduSessionCreatedData) SetEnablePauseCharging(v bool) {
	o.EnablePauseCharging = &v
}

// GetUeIpv4Address returns the UeIpv4Address field value if set, zero value otherwise.
func (o *PduSessionCreatedData) GetUeIpv4Address() string {
	if o == nil || IsNil(o.UeIpv4Address) {
		var ret string
		return ret
	}
	return *o.UeIpv4Address
}

// GetUeIpv4AddressOk returns a tuple with the UeIpv4Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreatedData) GetUeIpv4AddressOk() (*string, bool) {
	if o == nil || IsNil(o.UeIpv4Address) {
		return nil, false
	}
	return o.UeIpv4Address, true
}

// HasUeIpv4Address returns a boolean if a field has been set.
func (o *PduSessionCreatedData) HasUeIpv4Address() bool {
	if o != nil && !IsNil(o.UeIpv4Address) {
		return true
	}

	return false
}

// SetUeIpv4Address gets a reference to the given string and assigns it to the UeIpv4Address field.
func (o *PduSessionCreatedData) SetUeIpv4Address(v string) {
	o.UeIpv4Address = &v
}

// GetUeIpv6Prefix returns the UeIpv6Prefix field value if set, zero value otherwise.
func (o *PduSessionCreatedData) GetUeIpv6Prefix() Ipv6Prefix {
	if o == nil || IsNil(o.UeIpv6Prefix) {
		var ret Ipv6Prefix
		return ret
	}
	return *o.UeIpv6Prefix
}

// GetUeIpv6PrefixOk returns a tuple with the UeIpv6Prefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreatedData) GetUeIpv6PrefixOk() (*Ipv6Prefix, bool) {
	if o == nil || IsNil(o.UeIpv6Prefix) {
		return nil, false
	}
	return o.UeIpv6Prefix, true
}

// HasUeIpv6Prefix returns a boolean if a field has been set.
func (o *PduSessionCreatedData) HasUeIpv6Prefix() bool {
	if o != nil && !IsNil(o.UeIpv6Prefix) {
		return true
	}

	return false
}

// SetUeIpv6Prefix gets a reference to the given Ipv6Prefix and assigns it to the UeIpv6Prefix field.
func (o *PduSessionCreatedData) SetUeIpv6Prefix(v Ipv6Prefix) {
	o.UeIpv6Prefix = &v
}

// GetN1SmInfoToUe returns the N1SmInfoToUe field value if set, zero value otherwise.
func (o *PduSessionCreatedData) GetN1SmInfoToUe() RefToBinaryData {
	if o == nil || IsNil(o.N1SmInfoToUe) {
		var ret RefToBinaryData
		return ret
	}
	return *o.N1SmInfoToUe
}

// GetN1SmInfoToUeOk returns a tuple with the N1SmInfoToUe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreatedData) GetN1SmInfoToUeOk() (*RefToBinaryData, bool) {
	if o == nil || IsNil(o.N1SmInfoToUe) {
		return nil, false
	}
	return o.N1SmInfoToUe, true
}

// HasN1SmInfoToUe returns a boolean if a field has been set.
func (o *PduSessionCreatedData) HasN1SmInfoToUe() bool {
	if o != nil && !IsNil(o.N1SmInfoToUe) {
		return true
	}

	return false
}

// SetN1SmInfoToUe gets a reference to the given RefToBinaryData and assigns it to the N1SmInfoToUe field.
func (o *PduSessionCreatedData) SetN1SmInfoToUe(v RefToBinaryData) {
	o.N1SmInfoToUe = &v
}

// GetEpsPdnCnxInfo returns the EpsPdnCnxInfo field value if set, zero value otherwise.
func (o *PduSessionCreatedData) GetEpsPdnCnxInfo() EpsPdnCnxInfo {
	if o == nil || IsNil(o.EpsPdnCnxInfo) {
		var ret EpsPdnCnxInfo
		return ret
	}
	return *o.EpsPdnCnxInfo
}

// GetEpsPdnCnxInfoOk returns a tuple with the EpsPdnCnxInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreatedData) GetEpsPdnCnxInfoOk() (*EpsPdnCnxInfo, bool) {
	if o == nil || IsNil(o.EpsPdnCnxInfo) {
		return nil, false
	}
	return o.EpsPdnCnxInfo, true
}

// HasEpsPdnCnxInfo returns a boolean if a field has been set.
func (o *PduSessionCreatedData) HasEpsPdnCnxInfo() bool {
	if o != nil && !IsNil(o.EpsPdnCnxInfo) {
		return true
	}

	return false
}

// SetEpsPdnCnxInfo gets a reference to the given EpsPdnCnxInfo and assigns it to the EpsPdnCnxInfo field.
func (o *PduSessionCreatedData) SetEpsPdnCnxInfo(v EpsPdnCnxInfo) {
	o.EpsPdnCnxInfo = &v
}

// GetEpsBearerInfo returns the EpsBearerInfo field value if set, zero value otherwise.
func (o *PduSessionCreatedData) GetEpsBearerInfo() []EpsBearerInfo {
	if o == nil || IsNil(o.EpsBearerInfo) {
		var ret []EpsBearerInfo
		return ret
	}
	return o.EpsBearerInfo
}

// GetEpsBearerInfoOk returns a tuple with the EpsBearerInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreatedData) GetEpsBearerInfoOk() ([]EpsBearerInfo, bool) {
	if o == nil || IsNil(o.EpsBearerInfo) {
		return nil, false
	}
	return o.EpsBearerInfo, true
}

// HasEpsBearerInfo returns a boolean if a field has been set.
func (o *PduSessionCreatedData) HasEpsBearerInfo() bool {
	if o != nil && !IsNil(o.EpsBearerInfo) {
		return true
	}

	return false
}

// SetEpsBearerInfo gets a reference to the given []EpsBearerInfo and assigns it to the EpsBearerInfo field.
func (o *PduSessionCreatedData) SetEpsBearerInfo(v []EpsBearerInfo) {
	o.EpsBearerInfo = v
}

// GetSupportedFeatures returns the SupportedFeatures field value if set, zero value otherwise.
func (o *PduSessionCreatedData) GetSupportedFeatures() string {
	if o == nil || IsNil(o.SupportedFeatures) {
		var ret string
		return ret
	}
	return *o.SupportedFeatures
}

// GetSupportedFeaturesOk returns a tuple with the SupportedFeatures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreatedData) GetSupportedFeaturesOk() (*string, bool) {
	if o == nil || IsNil(o.SupportedFeatures) {
		return nil, false
	}
	return o.SupportedFeatures, true
}

// HasSupportedFeatures returns a boolean if a field has been set.
func (o *PduSessionCreatedData) HasSupportedFeatures() bool {
	if o != nil && !IsNil(o.SupportedFeatures) {
		return true
	}

	return false
}

// SetSupportedFeatures gets a reference to the given string and assigns it to the SupportedFeatures field.
func (o *PduSessionCreatedData) SetSupportedFeatures(v string) {
	o.SupportedFeatures = &v
}

// GetMaxIntegrityProtectedDataRate returns the MaxIntegrityProtectedDataRate field value if set, zero value otherwise.
func (o *PduSessionCreatedData) GetMaxIntegrityProtectedDataRate() MaxIntegrityProtectedDataRate {
	if o == nil || IsNil(o.MaxIntegrityProtectedDataRate) {
		var ret MaxIntegrityProtectedDataRate
		return ret
	}
	return *o.MaxIntegrityProtectedDataRate
}

// GetMaxIntegrityProtectedDataRateOk returns a tuple with the MaxIntegrityProtectedDataRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreatedData) GetMaxIntegrityProtectedDataRateOk() (*MaxIntegrityProtectedDataRate, bool) {
	if o == nil || IsNil(o.MaxIntegrityProtectedDataRate) {
		return nil, false
	}
	return o.MaxIntegrityProtectedDataRate, true
}

// HasMaxIntegrityProtectedDataRate returns a boolean if a field has been set.
func (o *PduSessionCreatedData) HasMaxIntegrityProtectedDataRate() bool {
	if o != nil && !IsNil(o.MaxIntegrityProtectedDataRate) {
		return true
	}

	return false
}

// SetMaxIntegrityProtectedDataRate gets a reference to the given MaxIntegrityProtectedDataRate and assigns it to the MaxIntegrityProtectedDataRate field.
func (o *PduSessionCreatedData) SetMaxIntegrityProtectedDataRate(v MaxIntegrityProtectedDataRate) {
	o.MaxIntegrityProtectedDataRate = &v
}

// GetMaxIntegrityProtectedDataRateDl returns the MaxIntegrityProtectedDataRateDl field value if set, zero value otherwise.
func (o *PduSessionCreatedData) GetMaxIntegrityProtectedDataRateDl() MaxIntegrityProtectedDataRate {
	if o == nil || IsNil(o.MaxIntegrityProtectedDataRateDl) {
		var ret MaxIntegrityProtectedDataRate
		return ret
	}
	return *o.MaxIntegrityProtectedDataRateDl
}

// GetMaxIntegrityProtectedDataRateDlOk returns a tuple with the MaxIntegrityProtectedDataRateDl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreatedData) GetMaxIntegrityProtectedDataRateDlOk() (*MaxIntegrityProtectedDataRate, bool) {
	if o == nil || IsNil(o.MaxIntegrityProtectedDataRateDl) {
		return nil, false
	}
	return o.MaxIntegrityProtectedDataRateDl, true
}

// HasMaxIntegrityProtectedDataRateDl returns a boolean if a field has been set.
func (o *PduSessionCreatedData) HasMaxIntegrityProtectedDataRateDl() bool {
	if o != nil && !IsNil(o.MaxIntegrityProtectedDataRateDl) {
		return true
	}

	return false
}

// SetMaxIntegrityProtectedDataRateDl gets a reference to the given MaxIntegrityProtectedDataRate and assigns it to the MaxIntegrityProtectedDataRateDl field.
func (o *PduSessionCreatedData) SetMaxIntegrityProtectedDataRateDl(v MaxIntegrityProtectedDataRate) {
	o.MaxIntegrityProtectedDataRateDl = &v
}

// GetAlwaysOnGranted returns the AlwaysOnGranted field value if set, zero value otherwise.
func (o *PduSessionCreatedData) GetAlwaysOnGranted() bool {
	if o == nil || IsNil(o.AlwaysOnGranted) {
		var ret bool
		return ret
	}
	return *o.AlwaysOnGranted
}

// GetAlwaysOnGrantedOk returns a tuple with the AlwaysOnGranted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreatedData) GetAlwaysOnGrantedOk() (*bool, bool) {
	if o == nil || IsNil(o.AlwaysOnGranted) {
		return nil, false
	}
	return o.AlwaysOnGranted, true
}

// HasAlwaysOnGranted returns a boolean if a field has been set.
func (o *PduSessionCreatedData) HasAlwaysOnGranted() bool {
	if o != nil && !IsNil(o.AlwaysOnGranted) {
		return true
	}

	return false
}

// SetAlwaysOnGranted gets a reference to the given bool and assigns it to the AlwaysOnGranted field.
func (o *PduSessionCreatedData) SetAlwaysOnGranted(v bool) {
	o.AlwaysOnGranted = &v
}

// GetGpsi returns the Gpsi field value if set, zero value otherwise.
func (o *PduSessionCreatedData) GetGpsi() string {
	if o == nil || IsNil(o.Gpsi) {
		var ret string
		return ret
	}
	return *o.Gpsi
}

// GetGpsiOk returns a tuple with the Gpsi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreatedData) GetGpsiOk() (*string, bool) {
	if o == nil || IsNil(o.Gpsi) {
		return nil, false
	}
	return o.Gpsi, true
}

// HasGpsi returns a boolean if a field has been set.
func (o *PduSessionCreatedData) HasGpsi() bool {
	if o != nil && !IsNil(o.Gpsi) {
		return true
	}

	return false
}

// SetGpsi gets a reference to the given string and assigns it to the Gpsi field.
func (o *PduSessionCreatedData) SetGpsi(v string) {
	o.Gpsi = &v
}

// GetUpSecurity returns the UpSecurity field value if set, zero value otherwise.
func (o *PduSessionCreatedData) GetUpSecurity() UpSecurity {
	if o == nil || IsNil(o.UpSecurity) {
		var ret UpSecurity
		return ret
	}
	return *o.UpSecurity
}

// GetUpSecurityOk returns a tuple with the UpSecurity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreatedData) GetUpSecurityOk() (*UpSecurity, bool) {
	if o == nil || IsNil(o.UpSecurity) {
		return nil, false
	}
	return o.UpSecurity, true
}

// HasUpSecurity returns a boolean if a field has been set.
func (o *PduSessionCreatedData) HasUpSecurity() bool {
	if o != nil && !IsNil(o.UpSecurity) {
		return true
	}

	return false
}

// SetUpSecurity gets a reference to the given UpSecurity and assigns it to the UpSecurity field.
func (o *PduSessionCreatedData) SetUpSecurity(v UpSecurity) {
	o.UpSecurity = &v
}

// GetRoamingChargingProfile returns the RoamingChargingProfile field value if set, zero value otherwise.
func (o *PduSessionCreatedData) GetRoamingChargingProfile() RoamingChargingProfile {
	if o == nil || IsNil(o.RoamingChargingProfile) {
		var ret RoamingChargingProfile
		return ret
	}
	return *o.RoamingChargingProfile
}

// GetRoamingChargingProfileOk returns a tuple with the RoamingChargingProfile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreatedData) GetRoamingChargingProfileOk() (*RoamingChargingProfile, bool) {
	if o == nil || IsNil(o.RoamingChargingProfile) {
		return nil, false
	}
	return o.RoamingChargingProfile, true
}

// HasRoamingChargingProfile returns a boolean if a field has been set.
func (o *PduSessionCreatedData) HasRoamingChargingProfile() bool {
	if o != nil && !IsNil(o.RoamingChargingProfile) {
		return true
	}

	return false
}

// SetRoamingChargingProfile gets a reference to the given RoamingChargingProfile and assigns it to the RoamingChargingProfile field.
func (o *PduSessionCreatedData) SetRoamingChargingProfile(v RoamingChargingProfile) {
	o.RoamingChargingProfile = &v
}

// GetHSmfServiceInstanceId returns the HSmfServiceInstanceId field value if set, zero value otherwise.
func (o *PduSessionCreatedData) GetHSmfServiceInstanceId() string {
	if o == nil || IsNil(o.HSmfServiceInstanceId) {
		var ret string
		return ret
	}
	return *o.HSmfServiceInstanceId
}

// GetHSmfServiceInstanceIdOk returns a tuple with the HSmfServiceInstanceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreatedData) GetHSmfServiceInstanceIdOk() (*string, bool) {
	if o == nil || IsNil(o.HSmfServiceInstanceId) {
		return nil, false
	}
	return o.HSmfServiceInstanceId, true
}

// HasHSmfServiceInstanceId returns a boolean if a field has been set.
func (o *PduSessionCreatedData) HasHSmfServiceInstanceId() bool {
	if o != nil && !IsNil(o.HSmfServiceInstanceId) {
		return true
	}

	return false
}

// SetHSmfServiceInstanceId gets a reference to the given string and assigns it to the HSmfServiceInstanceId field.
func (o *PduSessionCreatedData) SetHSmfServiceInstanceId(v string) {
	o.HSmfServiceInstanceId = &v
}

// GetRecoveryTime returns the RecoveryTime field value if set, zero value otherwise.
func (o *PduSessionCreatedData) GetRecoveryTime() time.Time {
	if o == nil || IsNil(o.RecoveryTime) {
		var ret time.Time
		return ret
	}
	return *o.RecoveryTime
}

// GetRecoveryTimeOk returns a tuple with the RecoveryTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreatedData) GetRecoveryTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.RecoveryTime) {
		return nil, false
	}
	return o.RecoveryTime, true
}

// HasRecoveryTime returns a boolean if a field has been set.
func (o *PduSessionCreatedData) HasRecoveryTime() bool {
	if o != nil && !IsNil(o.RecoveryTime) {
		return true
	}

	return false
}

// SetRecoveryTime gets a reference to the given time.Time and assigns it to the RecoveryTime field.
func (o *PduSessionCreatedData) SetRecoveryTime(v time.Time) {
	o.RecoveryTime = &v
}

// GetUeIpv6InterfaceId returns the UeIpv6InterfaceId field value if set, zero value otherwise.
func (o *PduSessionCreatedData) GetUeIpv6InterfaceId() string {
	if o == nil || IsNil(o.UeIpv6InterfaceId) {
		var ret string
		return ret
	}
	return *o.UeIpv6InterfaceId
}

// GetUeIpv6InterfaceIdOk returns a tuple with the UeIpv6InterfaceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PduSessionCreatedData) GetUeIpv6InterfaceIdOk() (*string, bool) {
	if o == nil || IsNil(o.UeIpv6InterfaceId) {
		return nil, false
	}
	return o.UeIpv6InterfaceId, true
}

// HasUeIpv6InterfaceId returns a boolean if a field has been set.
func (o *PduSessionCreatedData) HasUeIpv6InterfaceId() bool {
	if o != nil && !IsNil(o.UeIpv6InterfaceId) {
		return true
	}

	return false
}

// SetUeIpv6InterfaceId gets a reference to the given string and assigns it to the UeIpv6InterfaceId field.
func (o *PduSessionCreatedData) SetUeIpv6InterfaceId(v string) {
	o.UeIpv6InterfaceId = &v
}

func (o PduSessionCreatedData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PduSessionCreatedData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pduSessionType"] = o.PduSessionType
	toSerialize["sscMode"] = o.SscMode
	toSerialize["hcnTunnelInfo"] = o.HcnTunnelInfo
	toSerialize["sessionAmbr"] = o.SessionAmbr
	toSerialize["qosFlowsSetupList"] = o.QosFlowsSetupList
	toSerialize["hSmfInstanceId"] = o.HSmfInstanceId
	if !IsNil(o.PduSessionId) {
		toSerialize["pduSessionId"] = o.PduSessionId
	}
	if !IsNil(o.SNssai) {
		toSerialize["sNssai"] = o.SNssai
	}
	if !IsNil(o.EnablePauseCharging) {
		toSerialize["enablePauseCharging"] = o.EnablePauseCharging
	}
	if !IsNil(o.UeIpv4Address) {
		toSerialize["ueIpv4Address"] = o.UeIpv4Address
	}
	if !IsNil(o.UeIpv6Prefix) {
		toSerialize["ueIpv6Prefix"] = o.UeIpv6Prefix
	}
	if !IsNil(o.N1SmInfoToUe) {
		toSerialize["n1SmInfoToUe"] = o.N1SmInfoToUe
	}
	if !IsNil(o.EpsPdnCnxInfo) {
		toSerialize["epsPdnCnxInfo"] = o.EpsPdnCnxInfo
	}
	if !IsNil(o.EpsBearerInfo) {
		toSerialize["epsBearerInfo"] = o.EpsBearerInfo
	}
	if !IsNil(o.SupportedFeatures) {
		toSerialize["supportedFeatures"] = o.SupportedFeatures
	}
	if !IsNil(o.MaxIntegrityProtectedDataRate) {
		toSerialize["maxIntegrityProtectedDataRate"] = o.MaxIntegrityProtectedDataRate
	}
	if !IsNil(o.MaxIntegrityProtectedDataRateDl) {
		toSerialize["maxIntegrityProtectedDataRateDl"] = o.MaxIntegrityProtectedDataRateDl
	}
	if !IsNil(o.AlwaysOnGranted) {
		toSerialize["alwaysOnGranted"] = o.AlwaysOnGranted
	}
	if !IsNil(o.Gpsi) {
		toSerialize["gpsi"] = o.Gpsi
	}
	if !IsNil(o.UpSecurity) {
		toSerialize["upSecurity"] = o.UpSecurity
	}
	if !IsNil(o.RoamingChargingProfile) {
		toSerialize["roamingChargingProfile"] = o.RoamingChargingProfile
	}
	if !IsNil(o.HSmfServiceInstanceId) {
		toSerialize["hSmfServiceInstanceId"] = o.HSmfServiceInstanceId
	}
	if !IsNil(o.RecoveryTime) {
		toSerialize["recoveryTime"] = o.RecoveryTime
	}
	if !IsNil(o.UeIpv6InterfaceId) {
		toSerialize["ueIpv6InterfaceId"] = o.UeIpv6InterfaceId
	}
	return toSerialize, nil
}

type NullablePduSessionCreatedData struct {
	value *PduSessionCreatedData
	isSet bool
}

func (v NullablePduSessionCreatedData) Get() *PduSessionCreatedData {
	return v.value
}

func (v *NullablePduSessionCreatedData) Set(val *PduSessionCreatedData) {
	v.value = val
	v.isSet = true
}

func (v NullablePduSessionCreatedData) IsSet() bool {
	return v.isSet
}

func (v *NullablePduSessionCreatedData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePduSessionCreatedData(val *PduSessionCreatedData) *NullablePduSessionCreatedData {
	return &NullablePduSessionCreatedData{value: val, isSet: true}
}

func (v NullablePduSessionCreatedData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePduSessionCreatedData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


