/*
Nsmf_PDUSession

SMF PDU Session Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

API version: 1.0.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
	"fmt"
)

// AdditionalQosFlowInfo struct for AdditionalQosFlowInfo
type AdditionalQosFlowInfo struct {
	string *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *AdditionalQosFlowInfo) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into string
	err = json.Unmarshal(data, &dst.string);
	if err == nil {
		jsonstring, _ := json.Marshal(dst.string)
		if string(jsonstring) == "{}" { // empty struct
			dst.string = nil
		} else {
			return nil // data stored in dst.string, return on the first match
		}
	} else {
		dst.string = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(AdditionalQosFlowInfo)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *AdditionalQosFlowInfo) MarshalJSON() ([]byte, error) {
	if src.string != nil {
		return json.Marshal(&src.string)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableAdditionalQosFlowInfo struct {
	value *AdditionalQosFlowInfo
	isSet bool
}

func (v NullableAdditionalQosFlowInfo) Get() *AdditionalQosFlowInfo {
	return v.value
}

func (v *NullableAdditionalQosFlowInfo) Set(val *AdditionalQosFlowInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableAdditionalQosFlowInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableAdditionalQosFlowInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdditionalQosFlowInfo(val *AdditionalQosFlowInfo) *NullableAdditionalQosFlowInfo {
	return &NullableAdditionalQosFlowInfo{value: val, isSet: true}
}

func (v NullableAdditionalQosFlowInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdditionalQosFlowInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


