/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapiserver

import (
	"encoding/json"
	"errors"
)

type QosFlowNotifyItem struct {
	Qfi int32 `json:"qfi"`

	NotificationCause NotificationCause `json:"notificationCause"`
}

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *QosFlowNotifyItem) UnmarshalJSON(data []byte) error {

	type Alias QosFlowNotifyItem // To avoid infinite recursion
	return json.Unmarshal(data, (*Alias)(m))
}

// AssertQosFlowNotifyItemRequired checks if the required fields are not zero-ed
func AssertQosFlowNotifyItemRequired(obj QosFlowNotifyItem) error {
	elements := map[string]interface{}{
		"qfi":               obj.Qfi,
		"notificationCause": obj.NotificationCause,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNotificationCauseRequired(obj.NotificationCause); err != nil {
		return err
	}
	return nil
}

// AssertQosFlowNotifyItemConstraints checks if the values respects the defined constraints
func AssertQosFlowNotifyItemConstraints(obj QosFlowNotifyItem) error {
	if obj.Qfi < 0 {
		return &ParsingError{Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.Qfi > 63 {
		return &ParsingError{Err: errors.New(errMsgMaxValueConstraint)}
	}
	return nil
}
