/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapiserver

import (
	"encoding/json"
	"os"
)

type UpdateSmContextRequest struct {
	JsonData SmContextUpdateData `json:"jsonData,omitempty"`

	BinaryDataN1SmMessage *os.File `json:"binaryDataN1SmMessage,omitempty"`

	BinaryDataN2SmInformation *os.File `json:"binaryDataN2SmInformation,omitempty"`

	BinaryDataN2SmInformationExt1 *os.File `json:"binaryDataN2SmInformationExt1,omitempty"`
}

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *UpdateSmContextRequest) UnmarshalJSON(data []byte) error {

	type Alias UpdateSmContextRequest // To avoid infinite recursion
	return json.Unmarshal(data, (*Alias)(m))
}

// AssertUpdateSmContextRequestRequired checks if the required fields are not zero-ed
func AssertUpdateSmContextRequestRequired(obj UpdateSmContextRequest) error {
	if err := AssertSmContextUpdateDataRequired(obj.JsonData); err != nil {
		return err
	}
	return nil
}

// AssertUpdateSmContextRequestConstraints checks if the values respects the defined constraints
func AssertUpdateSmContextRequestConstraints(obj UpdateSmContextRequest) error {
	return nil
}
