/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapiserver

import (
	"encoding/json"
)

// HoState - Possible values are - NONE - PREPARING - PREPARED - COMPLETED - CANCELLED
type HoState struct {
}

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *HoState) UnmarshalJSON(data []byte) error {

	type Alias HoState // To avoid infinite recursion
	return json.Unmarshal(data, (*Alias)(m))
}

// AssertHoStateRequired checks if the required fields are not zero-ed
func AssertHoStateRequired(obj HoState) error {
	return nil
}

// AssertHoStateConstraints checks if the values respects the defined constraints
func AssertHoStateConstraints(obj HoState) error {
	return nil
}
