/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapiserver

import (
	"encoding/json"
	"errors"
	"time"
)

type QosFlowUsageReport struct {
	Qfi int32 `json:"qfi"`

	StartTimeStamp time.Time `json:"startTimeStamp"`

	EndTimeStamp time.Time `json:"endTimeStamp"`

	DownlinkVolume int64 `json:"downlinkVolume"`

	UplinkVolume int64 `json:"uplinkVolume"`
}

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *QosFlowUsageReport) UnmarshalJSON(data []byte) error {

	type Alias QosFlowUsageReport // To avoid infinite recursion
	return json.Unmarshal(data, (*Alias)(m))
}

// AssertQosFlowUsageReportRequired checks if the required fields are not zero-ed
func AssertQosFlowUsageReportRequired(obj QosFlowUsageReport) error {
	elements := map[string]interface{}{
		"qfi":            obj.Qfi,
		"startTimeStamp": obj.StartTimeStamp,
		"endTimeStamp":   obj.EndTimeStamp,
		"downlinkVolume": obj.DownlinkVolume,
		"uplinkVolume":   obj.UplinkVolume,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertQosFlowUsageReportConstraints checks if the values respects the defined constraints
func AssertQosFlowUsageReportConstraints(obj QosFlowUsageReport) error {
	if obj.Qfi < 0 {
		return &ParsingError{Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.Qfi > 63 {
		return &ParsingError{Err: errors.New(errMsgMaxValueConstraint)}
	}
	return nil
}
