/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapiserver

import (
	"encoding/json"
)

// EpsInterworkingIndication - Possible values are - NONE - WITH_N26 - WITHOUT_N26
type EpsInterworkingIndication string

const (
	NONE         EpsInterworkingIndication = "NONE"
	WITH_N26     EpsInterworkingIndication = "WITH_N26"
	WITHOUT_N26  EpsInterworkingIndication = "WITHOUT_N26"
	IWK_NON_3GPP EpsInterworkingIndication = "IWK_NON_3GPP"
)

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *EpsInterworkingIndication) UnmarshalJSON(data []byte) error {

	type Alias EpsInterworkingIndication // To avoid infinite recursion
	return json.Unmarshal(data, (*Alias)(m))
}

// AssertEpsInterworkingIndicationRequired checks if the required fields are not zero-ed
func AssertEpsInterworkingIndicationRequired(obj EpsInterworkingIndication) error {
	return nil
}

// AssertEpsInterworkingIndicationConstraints checks if the values respects the defined constraints
func AssertEpsInterworkingIndicationConstraints(obj EpsInterworkingIndication) error {
	return nil
}
