/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapiserver

import (
	"encoding/json"
)

type NgRanTargetId struct {
	RanNodeId *GlobalRanNodeId `json:"ranNodeId"`

	Tai Tai `json:"tai"`
}

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *NgRanTargetId) UnmarshalJSON(data []byte) error {

	type Alias NgRanTargetId // To avoid infinite recursion
	return json.Unmarshal(data, (*Alias)(m))
}

// AssertNgRanTargetIdRequired checks if the required fields are not zero-ed
func AssertNgRanTargetIdRequired(obj NgRanTargetId) error {
	elements := map[string]interface{}{
		"ranNodeId": obj.RanNodeId,
		"tai":       obj.Tai,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if obj.RanNodeId != nil {
		if err := AssertGlobalRanNodeIdRequired(*obj.RanNodeId); err != nil {
			return err
		}
	}
	if err := AssertTaiRequired(obj.Tai); err != nil {
		return err
	}
	return nil
}

// AssertNgRanTargetIdConstraints checks if the values respects the defined constraints
func AssertNgRanTargetIdConstraints(obj NgRanTargetId) error {
	return nil
}
