/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapiserver

import (
	"encoding/json"
)

type SecondaryRatUsageInfo struct {
	SecondaryRatType RatType `json:"secondaryRatType"`

	QosFlowsUsageData []QosFlowUsageReport `json:"qosFlowsUsageData,omitempty"`

	PduSessionUsageData []VolumeTimedReport `json:"pduSessionUsageData,omitempty"`
}

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *SecondaryRatUsageInfo) UnmarshalJSON(data []byte) error {

	type Alias SecondaryRatUsageInfo // To avoid infinite recursion
	return json.Unmarshal(data, (*Alias)(m))
}

// AssertSecondaryRatUsageInfoRequired checks if the required fields are not zero-ed
func AssertSecondaryRatUsageInfoRequired(obj SecondaryRatUsageInfo) error {
	elements := map[string]interface{}{
		"secondaryRatType": obj.SecondaryRatType,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertRatTypeRequired(obj.SecondaryRatType); err != nil {
		return err
	}
	for _, el := range obj.QosFlowsUsageData {
		if err := AssertQosFlowUsageReportRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.PduSessionUsageData {
		if err := AssertVolumeTimedReportRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertSecondaryRatUsageInfoConstraints checks if the values respects the defined constraints
func AssertSecondaryRatUsageInfoConstraints(obj SecondaryRatUsageInfo) error {
	return nil
}
