/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapiserver

import (
	"encoding/json"
	"os"
)

type ModifyPduSessionRequest struct {
	JsonData VsmfUpdateData `json:"jsonData,omitempty"`

	BinaryDataN1SmInfoToUe *os.File `json:"binaryDataN1SmInfoToUe,omitempty"`
}

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *ModifyPduSessionRequest) UnmarshalJSON(data []byte) error {

	type Alias ModifyPduSessionRequest // To avoid infinite recursion
	return json.Unmarshal(data, (*Alias)(m))
}

// AssertModifyPduSessionRequestRequired checks if the required fields are not zero-ed
func AssertModifyPduSessionRequestRequired(obj ModifyPduSessionRequest) error {
	if err := AssertVsmfUpdateDataRequired(obj.JsonData); err != nil {
		return err
	}
	return nil
}

// AssertModifyPduSessionRequestConstraints checks if the values respects the defined constraints
func AssertModifyPduSessionRequestConstraints(obj ModifyPduSessionRequest) error {
	return nil
}
