/*
 * Namf_Communication
 *
 * AMF Communication Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_commn_server

import (
	"encoding/json"
)

type N1N2MessageTransferRspData struct {
	Cause N1N2MessageTransferCause `json:"cause"`

	SupportedFeatures string `json:"supportedFeatures,omitempty"`
}

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *N1N2MessageTransferRspData) UnmarshalJSON(data []byte) error {

	type Alias N1N2MessageTransferRspData // To avoid infinite recursion
	return json.Unmarshal(data, (*Alias)(m))
}

// AssertN1N2MessageTransferRspDataRequired checks if the required fields are not zero-ed
func AssertN1N2MessageTransferRspDataRequired(obj N1N2MessageTransferRspData) error {
	elements := map[string]interface{}{
		"cause": obj.Cause,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertN1N2MessageTransferCauseRequired(obj.Cause); err != nil {
		return err
	}
	return nil
}

// AssertN1N2MessageTransferRspDataConstraints checks if the values respects the defined constraints
func AssertN1N2MessageTransferRspDataConstraints(obj N1N2MessageTransferRspData) error {
	return nil
}
