/*
 * Namf_Communication
 *
 * AMF Communication Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.8
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_commn_server

import (
	"encoding/json"
	"errors"
)

type Arp struct {

	// nullable true shall not be used for this attribute
	PriorityLevel *int32 `json:"priorityLevel"`

	PreemptCap PreemptionCapability `json:"preemptCap"`

	PreemptVuln PreemptionVulnerability `json:"preemptVuln"`
}

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *Arp) UnmarshalJSON(data []byte) error {

	type Alias Arp // To avoid infinite recursion
	return json.Unmarshal(data, (*Alias)(m))
}

// AssertArpRequired checks if the required fields are not zero-ed
func AssertArpRequired(obj Arp) error {
	elements := map[string]interface{}{
		"priorityLevel": obj.PriorityLevel,
		"preemptCap":    obj.PreemptCap,
		"preemptVuln":   obj.PreemptVuln,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertPreemptionCapabilityRequired(obj.PreemptCap); err != nil {
		return err
	}
	if err := AssertPreemptionVulnerabilityRequired(obj.PreemptVuln); err != nil {
		return err
	}
	return nil
}

// AssertArpConstraints checks if the values respects the defined constraints
func AssertArpConstraints(obj Arp) error {
	if obj.PriorityLevel != nil && *obj.PriorityLevel < 1 {
		return &ParsingError{Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.PriorityLevel != nil && *obj.PriorityLevel > 15 {
		return &ParsingError{Err: errors.New(errMsgMaxValueConstraint)}
	}
	return nil
}
