// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.12.4
// source: n1n2messagetransfer.proto

package n1n2messagetransfer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type N1N2Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	N1DataBytes []byte `protobuf:"bytes,1,opt,name=N1DataBytes,proto3" json:"N1DataBytes,omitempty"`
	N2DataBytes []byte `protobuf:"bytes,2,opt,name=N2DataBytes,proto3" json:"N2DataBytes,omitempty"`
	UeContextId string `protobuf:"bytes,3,opt,name=UeContextId,proto3" json:"UeContextId,omitempty"`
}

func (x *N1N2Data) Reset() {
	*x = N1N2Data{}
	mi := &file_n1n2messagetransfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *N1N2Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*N1N2Data) ProtoMessage() {}

func (x *N1N2Data) ProtoReflect() protoreflect.Message {
	mi := &file_n1n2messagetransfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use N1N2Data.ProtoReflect.Descriptor instead.
func (*N1N2Data) Descriptor() ([]byte, []int) {
	return file_n1n2messagetransfer_proto_rawDescGZIP(), []int{0}
}

func (x *N1N2Data) GetN1DataBytes() []byte {
	if x != nil {
		return x.N1DataBytes
	}
	return nil
}

func (x *N1N2Data) GetN2DataBytes() []byte {
	if x != nil {
		return x.N2DataBytes
	}
	return nil
}

func (x *N1N2Data) GetUeContextId() string {
	if x != nil {
		return x.UeContextId
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err string `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_n1n2messagetransfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_n1n2messagetransfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_n1n2messagetransfer_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_n1n2messagetransfer_proto protoreflect.FileDescriptor

var file_n1n2messagetransfer_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6e, 0x31, 0x6e, 0x32, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70,
	0x63, 0x22, 0x70, 0x0a, 0x08, 0x4e, 0x31, 0x4e, 0x32, 0x44, 0x61, 0x74, 0x61, 0x12, 0x20, 0x0a,
	0x0b, 0x4e, 0x31, 0x44, 0x61, 0x74, 0x61, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0b, 0x4e, 0x31, 0x44, 0x61, 0x74, 0x61, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12,
	0x20, 0x0a, 0x0b, 0x4e, 0x32, 0x44, 0x61, 0x74, 0x61, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x4e, 0x32, 0x44, 0x61, 0x74, 0x61, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x12, 0x20, 0x0a, 0x0b, 0x55, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x55, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78,
	0x74, 0x49, 0x64, 0x22, 0x19, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x10, 0x0a, 0x03,
	0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x32, 0x49,
	0x0a, 0x10, 0x4e, 0x31, 0x4e, 0x32, 0x44, 0x61, 0x74, 0x61, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x12, 0x35, 0x0a, 0x14, 0x53, 0x65, 0x6e, 0x64, 0x4e, 0x31, 0x4e, 0x32, 0x44, 0x61,
	0x74, 0x61, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x0e, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x4e, 0x31, 0x4e, 0x32, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x0b, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x00, 0x42, 0x17, 0x5a, 0x15, 0x2e, 0x2f, 0x6e,
	0x31, 0x6e, 0x32, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_n1n2messagetransfer_proto_rawDescOnce sync.Once
	file_n1n2messagetransfer_proto_rawDescData = file_n1n2messagetransfer_proto_rawDesc
)

func file_n1n2messagetransfer_proto_rawDescGZIP() []byte {
	file_n1n2messagetransfer_proto_rawDescOnce.Do(func() {
		file_n1n2messagetransfer_proto_rawDescData = protoimpl.X.CompressGZIP(file_n1n2messagetransfer_proto_rawDescData)
	})
	return file_n1n2messagetransfer_proto_rawDescData
}

var file_n1n2messagetransfer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_n1n2messagetransfer_proto_goTypes = []any{
	(*N1N2Data)(nil), // 0: grpc.N1N2Data
	(*Error)(nil),    // 1: grpc.Error
}
var file_n1n2messagetransfer_proto_depIdxs = []int32{
	0, // 0: grpc.N1N2DataTransfer.SendN1N2DataTransfer:input_type -> grpc.N1N2Data
	1, // 1: grpc.N1N2DataTransfer.SendN1N2DataTransfer:output_type -> grpc.Error
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_n1n2messagetransfer_proto_init() }
func file_n1n2messagetransfer_proto_init() {
	if File_n1n2messagetransfer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_n1n2messagetransfer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_n1n2messagetransfer_proto_goTypes,
		DependencyIndexes: file_n1n2messagetransfer_proto_depIdxs,
		MessageInfos:      file_n1n2messagetransfer_proto_msgTypes,
	}.Build()
	File_n1n2messagetransfer_proto = out.File
	file_n1n2messagetransfer_proto_rawDesc = nil
	file_n1n2messagetransfer_proto_goTypes = nil
	file_n1n2messagetransfer_proto_depIdxs = nil
}
