/*
Namf_Communication

AMF Communication Service © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

API version: 1.0.8
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_commn_client

import (
	"encoding/json"
	"fmt"
	"k8s.io/klog"
)

// PreemptionCapability struct for PreemptionCapability
type PreemptionCapability struct {
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *PreemptionCapability) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into string
	err = json.Unmarshal(data, &dst.String);
	klog.Infof("%s", *dst.String)
	if err == nil {
		jsonstring, _ := json.Marshal(dst.String)
		klog.Infof("%s", jsonstring)
		if string(jsonstring) == "{}" { // empty struct
			klog.Infof("inside if %s", string(jsonstring))
			dst.String = nil
		} else {
			klog.Infof("inside else")
			return nil // data stored in dst.string, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(PreemptionCapability)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *PreemptionCapability) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}

type NullablePreemptionCapability struct {
	value *PreemptionCapability
	isSet bool
}

func (v NullablePreemptionCapability) Get() *PreemptionCapability {
	return v.value
}

func (v *NullablePreemptionCapability) Set(val *PreemptionCapability) {
	v.value = val
	v.isSet = true
}

func (v NullablePreemptionCapability) IsSet() bool {
	return v.isSet
}

func (v *NullablePreemptionCapability) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePreemptionCapability(val *PreemptionCapability) *NullablePreemptionCapability {
	return &NullablePreemptionCapability{value: val, isSet: true}
}

func (v NullablePreemptionCapability) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePreemptionCapability) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


