/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapiserver

import (
	"encoding/json"
)

type PlmnId struct {
	Mcc string `json:"mcc"`

	Mnc string `json:"mnc"`
}

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *PlmnId) UnmarshalJSON(data []byte) error {

	type Alias PlmnId // To avoid infinite recursion
	return json.Unmarshal(data, (*Alias)(m))
}

// AssertPlmnIdRequired checks if the required fields are not zero-ed
func AssertPlmnIdRequired(obj PlmnId) error {
	elements := map[string]interface{}{
		"mcc": obj.Mcc,
		"mnc": obj.Mnc,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertPlmnIdConstraints checks if the values respects the defined constraints
func AssertPlmnIdConstraints(obj PlmnId) error {
	return nil
}
