/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapiserver

import (
	"encoding/json"
)

// RequestType - Possible values are - INITIAL_REQUEST - EXISTING_PDU_SESSION - INITIAL_EMERGENCY_REQUEST - EXISTING_EMERGENCY_PDU_SESSION
type RequestType string

const (
	INITIAL_REQUEST                RequestType = "INITIAL_REQUEST"
	EXISTING_PDU_SESSION           RequestType = "EXISTING_PDU_SESSION"
	INITIAL_EMERGENCY_REQUEST      RequestType = "INITIAL_EMERGENCY_REQUEST"
	EXISTING_EMERGENCY_PDU_SESSION RequestType = "EXISTING_EMERGENCY_PDU_SESSION"
)

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *RequestType) UnmarshalJSON(data []byte) error {

	type Alias RequestType // To avoid infinite recursion
	return json.Unmarshal(data, (*Alias)(m))
}

// AssertRequestTypeRequired checks if the required fields are not zero-ed
func AssertRequestTypeRequired(obj RequestType) error {
	return nil
}

// AssertRequestTypeConstraints checks if the values respects the defined constraints
func AssertRequestTypeConstraints(obj RequestType) error {
	return nil
}
