/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapiserver

import (
	"encoding/json"
)

type PduSessionNotifyItem struct {
	NotificationCause NotificationCause `json:"notificationCause"`
}

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *PduSessionNotifyItem) UnmarshalJSON(data []byte) error {

	type Alias PduSessionNotifyItem // To avoid infinite recursion
	return json.Unmarshal(data, (*Alias)(m))
}

// AssertPduSessionNotifyItemRequired checks if the required fields are not zero-ed
func AssertPduSessionNotifyItemRequired(obj PduSessionNotifyItem) error {
	elements := map[string]interface{}{
		"notificationCause": obj.NotificationCause,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNotificationCauseRequired(obj.NotificationCause); err != nil {
		return err
	}
	return nil
}

// AssertPduSessionNotifyItemConstraints checks if the values respects the defined constraints
func AssertPduSessionNotifyItemConstraints(obj PduSessionNotifyItem) error {
	return nil
}
