/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapiserver

import (
	"encoding/json"
)

type InvalidParam struct {
	Param string `json:"param"`

	Reason string `json:"reason,omitempty"`
}

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *InvalidParam) UnmarshalJSON(data []byte) error {

	type Alias InvalidParam // To avoid infinite recursion
	return json.Unmarshal(data, (*Alias)(m))
}

// AssertInvalidParamRequired checks if the required fields are not zero-ed
func AssertInvalidParamRequired(obj InvalidParam) error {
	elements := map[string]interface{}{
		"param": obj.Param,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertInvalidParamConstraints checks if the values respects the defined constraints
func AssertInvalidParamConstraints(obj InvalidParam) error {
	return nil
}
