/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapiserver

import (
	"encoding/json"
)

// UpCnxState - Possible values are - ACTIVATED - DEACTIVATED - ACTIVATING
type UpCnxState int

const (
	ACTIVATING  UpCnxState = iota + 1 // EnumIndex = 1
	ACTIVATED                         // EnumIndex = 2
	DEACTIVATED                       // EnumIndex = 3
)

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *UpCnxState) UnmarshalJSON(data []byte) error {

	type Alias UpCnxState // To avoid infinite recursion
	return json.Unmarshal(data, (*Alias)(m))
}

// AssertUpCnxStateRequired checks if the required fields are not zero-ed
func AssertUpCnxStateRequired(obj UpCnxState) error {
	return nil
}

// AssertUpCnxStateConstraints checks if the values respects the defined constraints
func AssertUpCnxStateConstraints(obj UpCnxState) error {
	return nil
}
