/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapiserver

import (
	"encoding/json"
	"errors"
)

type GbrQosFlowInformation struct {
	MaxFbrDl string `json:"maxFbrDl"`

	MaxFbrUl string `json:"maxFbrUl"`

	GuaFbrDl string `json:"guaFbrDl"`

	GuaFbrUl string `json:"guaFbrUl"`

	NotifControl NotificationControl `json:"notifControl,omitempty"`

	MaxPacketLossRateDl int32 `json:"maxPacketLossRateDl,omitempty"`

	MaxPacketLossRateUl int32 `json:"maxPacketLossRateUl,omitempty"`
}

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *GbrQosFlowInformation) UnmarshalJSON(data []byte) error {

	type Alias GbrQosFlowInformation // To avoid infinite recursion
	return json.Unmarshal(data, (*Alias)(m))
}

// AssertGbrQosFlowInformationRequired checks if the required fields are not zero-ed
func AssertGbrQosFlowInformationRequired(obj GbrQosFlowInformation) error {
	elements := map[string]interface{}{
		"maxFbrDl": obj.MaxFbrDl,
		"maxFbrUl": obj.MaxFbrUl,
		"guaFbrDl": obj.GuaFbrDl,
		"guaFbrUl": obj.GuaFbrUl,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertNotificationControlRequired(obj.NotifControl); err != nil {
		return err
	}
	return nil
}

// AssertGbrQosFlowInformationConstraints checks if the values respects the defined constraints
func AssertGbrQosFlowInformationConstraints(obj GbrQosFlowInformation) error {
	if obj.MaxPacketLossRateDl < 0 {
		return &ParsingError{Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.MaxPacketLossRateDl > 1000 {
		return &ParsingError{Err: errors.New(errMsgMaxValueConstraint)}
	}
	if obj.MaxPacketLossRateUl < 0 {
		return &ParsingError{Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.MaxPacketLossRateUl > 1000 {
		return &ParsingError{Err: errors.New(errMsgMaxValueConstraint)}
	}
	return nil
}
