/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapiserver

import (
	"encoding/json"
	"os"
)

type ModifyPduSession400Response struct {
	JsonData VsmfUpdateError `json:"jsonData,omitempty"`

	BinaryDataN1SmInfoFromUe *os.File `json:"binaryDataN1SmInfoFromUe,omitempty"`

	BinaryDataUnknownN1SmInfo *os.File `json:"binaryDataUnknownN1SmInfo,omitempty"`
}

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *ModifyPduSession400Response) UnmarshalJSON(data []byte) error {

	type Alias ModifyPduSession400Response // To avoid infinite recursion
	return json.Unmarshal(data, (*Alias)(m))
}

// AssertModifyPduSession400ResponseRequired checks if the required fields are not zero-ed
func AssertModifyPduSession400ResponseRequired(obj ModifyPduSession400Response) error {
	if err := AssertVsmfUpdateErrorRequired(obj.JsonData); err != nil {
		return err
	}
	return nil
}

// AssertModifyPduSession400ResponseConstraints checks if the values respects the defined constraints
func AssertModifyPduSession400ResponseConstraints(obj ModifyPduSession400Response) error {
	return nil
}
