/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 1.0.6
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapiserver

import (
	"encoding/json"
)

type Tai struct {
	PlmnId PlmnId `json:"plmnId"`

	Tac string `json:"tac"`
}

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *Tai) UnmarshalJSON(data []byte) error {

	type Alias Tai // To avoid infinite recursion
	return json.Unmarshal(data, (*Alias)(m))
}

// AssertTaiRequired checks if the required fields are not zero-ed
func AssertTaiRequired(obj Tai) error {
	elements := map[string]interface{}{
		"plmnId": obj.PlmnId,
		"tac":    obj.Tac,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertPlmnIdRequired(obj.PlmnId); err != nil {
		return err
	}
	return nil
}

// AssertTaiConstraints checks if the values respects the defined constraints
func AssertTaiConstraints(obj Tai) error {
	return nil
}
