package cs

type N1N2Message *interface{}

// 29.518  5.2.2.1
// type MessageType uint8

// const (
// 	UE_CONTEXT_TRANSFER_REQUEST         MessageType = 1
// 	UE_CONTEXT_TRANSFER_RESPONSE        MessageType = 2
// 	REGISTRATION_STATUS_UPDATE_REQUEST  MessageType = 3
// 	REGISTRATION_STATUS_UPDATE_RESPONSE MessageType = 4
// 	CREATE_UE_CONTEXT_REQUEST           MessageType = 5
// 	CREATE_UE_CONTEXT_RESPONSE          MessageType = 6
// 	RELEASE_UE_CONTEXT_REQUEST          MessageType = 7
// 	RELEASE_UE_CONTEXT_RESPONSE         MessageType = 8
// 	N1_MESSAGE_NOTIFY                   MessageType = 9
// 	N2_INFO_NOTIFY                      MessageType = 10
// 	N1_N2_MESSAGE_SUBSCRIBE             MessageType = 11
// 	N1_N2_MESSAGE_UNSUBSCRIBE           MessageType = 12
// 	N1_N2_MESSAGE_TRANSFER_REQUEST      MessageType = 13
// 	N1_N2_MESSAGE_TRANSFER_RESPONSE     MessageType = 14
// 	N1_N2_TRANSFER_FAILURE_NOTIFICATION MessageType = 15
// 	NON_UE_N2_MESSAGE_TRANSFER_REQUEST  MessageType = 16
// 	NON_UE_N2_MESSAGE_TRANSFER_RESPONSE MessageType = 17
// 	NON_UE_N2_INFO_SUBSCRIBE            MessageType = 18
// 	NON_UE_N2_INFO_UNSUBSCRIBE          MessageType = 19
// 	NON_UE_N2_INFO_NOTIFY               MessageType = 20
// 	EBI_ASSIGNMENT_REQUEST              MessageType = 21
// 	EBI_ASSIGNMENT_RESPONSE             MessageType = 22
// 	AMF_STATUS_CHANGE_SUBSCRIBE         MessageType = 23
// 	AMF_STATUS_CHANGE_UNSUBSCRIBE       MessageType = 24
// 	AMF_STATUS_CHANGE_NOTIFY            MessageType = 25
// )

// 29.518  5.2.2.3.1.1
type N1N2TransferProcedure uint8

const (
	NETWORK_TRIGGERED_SERVICE_REQUEST N1N2TransferProcedure = iota + 1
	PDU_SESSION_ESTABLISHMENT
	PDU_SESSION_MODIFICATION
	PDU_SESSION_RELEASE
	SESSION_CONTINUITY_SERVICE_CONTINUITY_AND_UP_PATH_MANAGEMENT
	INTER_NG_RAN_NODE_N2_BASED_HANDOVER
	SMS_OVER_NAS_PROCEDURES
	UE_ASSISTED_AND_UE_BASED_POSITIONING_PROCEDURE
	NETWORK_ASSISTED_POSITIONING_PROCEDURE
	UE_CONFIGURATION_UPDATE_PROCEDURE_FOR_TRANSPARENT_UE_POLICY_DELIVERY
)
